import packageJson from "../../package.json";
import type { ItemId, Language, Recipe, WorkstationId } from "./types";

export const uiText = {
  en: {
    activeTarget: "Current target",
    crewPerMachine: "Crew per machine",
    flow: "Flow",
    language: "Language",
    machineCount: "Machine count",
    machines: "Machines",
    output: "Output",
    perMachine: "per machine",
    rawDemand: "Raw demand",
    rawInputs: "Raw inputs",
    rawSource: "Raw source",
    recipeRules: "Recipe rules",
    sourcesInPlan: "Sources in plan",
    targetRate: "Target rate",
    wikiData: "Wiki data",
    with: "with",
    chooseItem: "Choose item",
    productionPlan: "Production plan",
  },
  de: {
    activeTarget: "Aktives Ziel",
    crewPerMachine: "Besetzung pro Maschine",
    flow: "Ablauf",
    language: "Sprache",
    machineCount: "Maschinenanzahl",
    machines: "Maschinen",
    output: "Output",
    perMachine: "je Maschine",
    rawDemand: "Rohbedarf",
    rawInputs: "Rohinputs",
    rawSource: "Quelle",
    recipeRules: "Rezeptregeln",
    sourcesInPlan: "Quellen im Plan",
    targetRate: "Zielrate",
    wikiData: "Wiki-Daten",
    with: "mit",
    chooseItem: "Item waehlen",
    productionPlan: "Produktionsplan",
  },
} satisfies Record<Language, Record<string, string>>;

export const appVersion = packageJson.version;

export const githubUrl = "https://github.com/sirkyomi/sparkulator";
const wikiBase = "https://oddsparks.wiki.gg/wiki/";

type ItemGroup =
  | "woodland"
  | "mountain"
  | "magic"
  | "cave"
  | "plateau"
  | "botanical"
  | "spark";

export const items: Record<
  ItemId,
  { name: string; image: string; wiki: string; group: ItemGroup }
> = {
  "beelephant-carapace": {
    name: "Beelephant Carapace",
    image: "/oddsparks/beelephant-carapace.png",
    wiki: `${wikiBase}Beelephant_Carapace`,
    group: "woodland",
  },
  coal: {
    name: "Coal",
    image: "/oddsparks/coal.png",
    wiki: `${wikiBase}Coal`,
    group: "woodland",
  },
  fabric: {
    name: "Fabric",
    image: "/oddsparks/fabric.png",
    wiki: `${wikiBase}Fabric`,
    group: "woodland",
  },
  fertiliser: {
    name: "Fertiliser",
    image: "/oddsparks/fertiliser.png",
    wiki: `${wikiBase}Fertiliser`,
    group: "woodland",
  },
  ladder: {
    name: "Ladder",
    image: "/oddsparks/ladder.png",
    wiki: `${wikiBase}Ladder`,
    group: "woodland",
  },
  leaves: {
    name: "Leaves",
    image: "/oddsparks/leaves.png",
    wiki: `${wikiBase}Leaves`,
    group: "woodland",
  },
  "mantis-stag-antler": {
    name: "Mantis Stag Antler",
    image: "/oddsparks/mantis-stag-antler.png",
    wiki: `${wikiBase}Mantis_Stag_Antler`,
    group: "woodland",
  },
  rope: {
    name: "Rope",
    image: "/oddsparks/rope.png",
    wiki: `${wikiBase}Rope`,
    group: "woodland",
  },
  "sawn-timber": {
    name: "Sawn Timber",
    image: "/oddsparks/sawn-timber.png",
    wiki: `${wikiBase}Sawn_Timber`,
    group: "woodland",
  },
  "tree-bark": {
    name: "Tree Bark",
    image: "/oddsparks/tree-bark.png",
    wiki: `${wikiBase}Tree_Bark`,
    group: "woodland",
  },
  "wooden-blade": {
    name: "Wooden Blade",
    image: "/oddsparks/wooden-blade.png",
    wiki: `${wikiBase}Wooden_Blade`,
    group: "woodland",
  },
  "wooden-log": {
    name: "Wooden Log",
    image: "/oddsparks/wooden-log.png",
    wiki: `${wikiBase}Wooden_Log`,
    group: "woodland",
  },
  "wooden-panel": {
    name: "Wooden Panel",
    image: "/oddsparks/wooden-panel.png",
    wiki: `${wikiBase}Wooden_Panel`,
    group: "woodland",
  },
  coral: {
    name: "Coral",
    image: "/oddsparks/coral.png",
    wiki: `${wikiBase}Coral`,
    group: "mountain",
  },
  "dowsing-stone": {
    name: "Dowsing Stone",
    image: "/oddsparks/dowsing-stone.png",
    wiki: `${wikiBase}Dowsing_Stone`,
    group: "mountain",
  },
  explosives: {
    name: "Explosives",
    image: "/oddsparks/explosives.png",
    wiki: `${wikiBase}Explosives`,
    group: "mountain",
  },
  "fluted-coral": {
    name: "Fluted Coral",
    image: "/oddsparks/fluted-coral.png",
    wiki: `${wikiBase}Fluted_Coral`,
    group: "mountain",
  },
  "frowl-sac": {
    name: "Frowl Sac",
    image: "/oddsparks/frowl-sac.png",
    wiki: `${wikiBase}Frowl_Sac`,
    group: "mountain",
  },
  "large-vial": {
    name: "Large Vial",
    image: "/oddsparks/large-vial.png",
    wiki: `${wikiBase}Large_Vial`,
    group: "mountain",
  },
  limestone: {
    name: "Limestone",
    image: "/oddsparks/limestone.png",
    wiki: `${wikiBase}Limestone`,
    group: "mountain",
  },
  "path-tile": {
    name: "Path Tile",
    image: "/oddsparks/path-tile.png",
    wiki: `${wikiBase}Path_Tile`,
    group: "mountain",
  },
  pebble: {
    name: "Pebble",
    image: "/oddsparks/pebble.png",
    wiki: `${wikiBase}Pebble`,
    group: "mountain",
  },
  "pengus-tendon": {
    name: "Pengus Tendon",
    image: "/oddsparks/pengus-tendon.png",
    wiki: `${wikiBase}Pengus_Tendon`,
    group: "mountain",
  },
  quartz: {
    name: "Quartz",
    image: "/oddsparks/quartz.png",
    wiki: `${wikiBase}Quartz`,
    group: "mountain",
  },
  "rock-teron-shell": {
    name: "Rock Teron Shell",
    image: "/oddsparks/rock-teron-shell.png",
    wiki: `${wikiBase}Rock_Teron_Shell`,
    group: "mountain",
  },
  "small-vial": {
    name: "Small Vial",
    image: "/oddsparks/small-vial.png",
    wiki: `${wikiBase}Small_Vial`,
    group: "mountain",
  },
  "squilican-tube": {
    name: "Squilican Tube",
    image: "/oddsparks/squilican-tube.png",
    wiki: `${wikiBase}Squilican_Tube`,
    group: "mountain",
  },
  stone: {
    name: "Stone",
    image: "/oddsparks/stone.png",
    wiki: `${wikiBase}Stone`,
    group: "mountain",
  },
  "stone-plate": {
    name: "Stone Plate",
    image: "/oddsparks/stone-plate.png",
    wiki: `${wikiBase}Stone_Plate`,
    group: "mountain",
  },
  "stone-spike": {
    name: "Stone Spike",
    image: "/oddsparks/stone-spike.png",
    wiki: `${wikiBase}Stone_Spike`,
    group: "mountain",
  },
  "stone-wheel": {
    name: "Stone Wheel",
    image: "/oddsparks/stone-wheel.png",
    wiki: `${wikiBase}Stone_Wheel`,
    group: "mountain",
  },
  "aether-crystal": {
    name: "Aether Crystal",
    image: "/oddsparks/aether-crystal.png",
    wiki: `${wikiBase}Aether_Crystal`,
    group: "magic",
  },
  "aether-shard": {
    name: "Aether Shard",
    image: "/oddsparks/aether-shard.png",
    wiki: `${wikiBase}Aether_Shard`,
    group: "magic",
  },
  "aetheric-clump": {
    name: "Aetheric Clump",
    image: "/oddsparks/aetheric-clump.png",
    wiki: `${wikiBase}Aetheric_Clump`,
    group: "magic",
  },
  "aetheric-pellet": {
    name: "Aetheric Pellet",
    image: "/oddsparks/aetheric-pellet.png",
    wiki: `${wikiBase}Aetheric_Pellet`,
    group: "magic",
  },
  fog: {
    name: "Fog",
    image: "/oddsparks/fog.png",
    wiki: `${wikiBase}Fog`,
    group: "magic",
  },
  "liquid-fertilizer": {
    name: "Liquid Fertilizer",
    image: "/oddsparks/liquid-fertilizer.png",
    wiki: `${wikiBase}Liquid_Fertilizer`,
    group: "magic",
  },
  miasma: {
    name: "Miasma",
    image: "/oddsparks/miasma.png",
    wiki: `${wikiBase}Miasma`,
    group: "magic",
  },
  "miasma-vial": {
    name: "Miasma Vial",
    image: "/oddsparks/miasma-vial.png",
    wiki: `${wikiBase}Miasma_Vial`,
    group: "magic",
  },
  "raw-aether": {
    name: "Raw Aether",
    image: "/oddsparks/raw-aether.png",
    wiki: `${wikiBase}Raw_Aether`,
    group: "magic",
  },
  "refined-aether": {
    name: "Refined Aether",
    image: "/oddsparks/refined-aether.png",
    wiki: `${wikiBase}Refined_Aether`,
    group: "magic",
  },
  "bumpy-geode": {
    name: "Bumpy Geode",
    image: "/oddsparks/bumpy-geode.png",
    wiki: `${wikiBase}Bumpy_Geode`,
    group: "cave",
  },
  "copper-ingot": {
    name: "Copper Ingot",
    image: "/oddsparks/copper-ingot.png",
    wiki: `${wikiBase}Copper_Ingot`,
    group: "cave",
  },
  "copper-ore": {
    name: "Copper Ore",
    image: "/oddsparks/copper-ore.png",
    wiki: `${wikiBase}Copper_Ore`,
    group: "cave",
  },
  "cracked-geode": {
    name: "Cracked Geode",
    image: "/oddsparks/cracked-geode.png",
    wiki: `${wikiBase}Cracked_Geode`,
    group: "cave",
  },
  "crangolin-lavascale": {
    name: "Crangolin Lavascale",
    image: "/oddsparks/crangolin-lavascale.png",
    wiki: `${wikiBase}Crangolin_Lavascale`,
    group: "cave",
  },
  "crangolin-scale": {
    name: "Crangolin Scale",
    image: "/oddsparks/crangolin-scale.png",
    wiki: `${wikiBase}Crangolin_Scale`,
    group: "cave",
  },
  "drill-bit": {
    name: "Drill Bit",
    image: "/oddsparks/drill-bit.png",
    wiki: `${wikiBase}Drill_Bit`,
    group: "cave",
  },
  glowshroom: {
    name: "Glowshroom",
    image: "/oddsparks/glowshroom.png",
    wiki: `${wikiBase}Glowshroom`,
    group: "cave",
  },
  "lava-cap": {
    name: "Lava Cap",
    image: "/oddsparks/lava-cap.png",
    wiki: `${wikiBase}Lava_Cap`,
    group: "cave",
  },
  "lava-shellhorse-comb": {
    name: "Lava Shellhorse Comb",
    image: "/oddsparks/lava-shellhorse-comb.png",
    wiki: `${wikiBase}Lava_Shellhorse_Comb`,
    group: "cave",
  },
  "shiny-geode": {
    name: "Shiny Geode",
    image: "/oddsparks/shiny-geode.png",
    wiki: `${wikiBase}Shiny_Geode`,
    group: "cave",
  },
  "volcanic-soil": {
    name: "Volcanic Soil",
    image: "/oddsparks/volcanic-soil.png",
    wiki: `${wikiBase}Volcanic_Soil`,
    group: "cave",
  },
  "frilled-walrion-tusk": {
    name: "Frilled Walrion Tusk",
    image: "/oddsparks/frilled-walrion-tusk.png",
    wiki: `${wikiBase}Frilled_Walrion_Tusk`,
    group: "plateau",
  },
  frost: {
    name: "Frost",
    image: "/oddsparks/frost.png",
    wiki: `${wikiBase}Frost`,
    group: "plateau",
  },
  "frozen-log": {
    name: "Frozen Log",
    image: "/oddsparks/frozen-log.png",
    wiki: `${wikiBase}Frozen_Log`,
    group: "plateau",
  },
  "frozen-stone": {
    name: "Frozen Stone",
    image: "/oddsparks/frozen-stone.png",
    wiki: `${wikiBase}Frozen_Stone`,
    group: "plateau",
  },
  "icehorn-ram-horn": {
    name: "Icehorn Ram Horn",
    image: "/oddsparks/icehorn-ram-horn.png",
    wiki: `${wikiBase}Icehorn_Ram_Horn`,
    group: "plateau",
  },
  "stellar-fertilizer": {
    name: "Stellar Fertilizer",
    image: "/oddsparks/stellar-fertilizer.png",
    wiki: `${wikiBase}Stellar_Fertilizer`,
    group: "plateau",
  },
  "stellar-ice": {
    name: "Stellar Ice",
    image: "/oddsparks/stellar-ice.png",
    wiki: `${wikiBase}Stellar_Ice`,
    group: "plateau",
  },
  "stellar-seed": {
    name: "Stellar Seed",
    image: "/oddsparks/stellar-seed.png",
    wiki: `${wikiBase}Stellar_Seed`,
    group: "plateau",
  },
  "aether-apple": {
    name: "Aether Apple",
    image: "/oddsparks/aether-apple.png",
    wiki: `${wikiBase}Aether_Apple`,
    group: "botanical",
  },
  "aether-flower": {
    name: "Aether Flower",
    image: "/oddsparks/aether-flower.png",
    wiki: `${wikiBase}Aether_Flower`,
    group: "botanical",
  },
  "aether-seed": {
    name: "Aether Seed",
    image: "/oddsparks/aether-seed.png",
    wiki: `${wikiBase}Aether_Seed`,
    group: "botanical",
  },
  "aether-segment": {
    name: "Aether Segment",
    image: "/oddsparks/aether-segment.png",
    wiki: `${wikiBase}Aether_Segment`,
    group: "botanical",
  },
  "copper-cuttings": {
    name: "Copper Cuttings",
    image: "/oddsparks/copper-cuttings.png",
    wiki: `${wikiBase}Copper_Cuttings`,
    group: "botanical",
  },
  "copper-sap": {
    name: "Copper Sap",
    image: "/oddsparks/copper-sap.png",
    wiki: `${wikiBase}Copper_Sap`,
    group: "botanical",
  },
  "copper-seed": {
    name: "Copper Seed",
    image: "/oddsparks/copper-seed.png",
    wiki: `${wikiBase}Copper_Seed`,
    group: "botanical",
  },
  "coral-seed": {
    name: "Coral Seed",
    image: "/oddsparks/coral-seed.png",
    wiki: `${wikiBase}Coral_Seed`,
    group: "botanical",
  },
  "fireshroom-cluster": {
    name: "Fireshroom Cluster",
    image: "/oddsparks/fireshroom-cluster.png",
    wiki: `${wikiBase}Fireshroom_Cluster`,
    group: "botanical",
  },
  "geode-cluster": {
    name: "Geode Cluster",
    image: "/oddsparks/geode-cluster.png",
    wiki: `${wikiBase}Geode_Cluster`,
    group: "botanical",
  },
  "leaf-knot": {
    name: "Leaf Knot",
    image: "/oddsparks/leaf-knot.png",
    wiki: `${wikiBase}Leaf_Knot`,
    group: "botanical",
  },
  "stellar-leaves": {
    name: "Stellar Leaves",
    image: "/oddsparks/stellar-leaves.png",
    wiki: `${wikiBase}Stellar_Leaves`,
    group: "botanical",
  },
  "arty-spark": {
    name: "Arty Spark",
    image: "/oddsparks/arty-spark.png",
    wiki: `${wikiBase}Arty_Spark`,
    group: "spark",
  },
  "boomy-spark": {
    name: "Boomy Spark",
    image: "/oddsparks/boomy-spark.png",
    wiki: `${wikiBase}Boomy_Spark`,
    group: "spark",
  },
  "carry-spark": {
    name: "Carry Spark",
    image: "/oddsparks/carry-spark.png",
    wiki: `${wikiBase}Carry_Spark`,
    group: "spark",
  },
  "choppy-spark": {
    name: "Choppy Spark",
    image: "/oddsparks/choppy-spark.png",
    wiki: `${wikiBase}Choppy_Spark`,
    group: "spark",
  },
  "crafty-spark": {
    name: "Crafty Spark",
    image: "/oddsparks/crafty-spark.png",
    wiki: `${wikiBase}Crafty_Spark`,
    group: "spark",
  },
  "crashy-spark": {
    name: "Crashy Spark",
    image: "/oddsparks/crashy-spark.png",
    wiki: `${wikiBase}Crashy_Spark`,
    group: "spark",
  },
  "drilly-spark": {
    name: "Drilly Spark",
    image: "/oddsparks/drilly-spark.png",
    wiki: `${wikiBase}Drilly_Spark`,
    group: "spark",
  },
  "handy-spark": {
    name: "Handy Spark",
    image: "/oddsparks/handy-spark.png",
    wiki: `${wikiBase}Handy_Spark`,
    group: "spark",
  },
  "hauling-spark": {
    name: "Hauling Spark",
    image: "/oddsparks/hauling-spark.png",
    wiki: `${wikiBase}Hauling_Spark`,
    group: "spark",
  },
  "loamy-spark": {
    name: "Loamy Spark",
    image: "/oddsparks/loamy-spark.png",
    wiki: `${wikiBase}Loamy_Spark`,
    group: "spark",
  },
  "puffy-spark": {
    name: "Puffy Spark",
    image: "/oddsparks/puffy-spark.png",
    wiki: `${wikiBase}Puffy_Spark`,
    group: "spark",
  },
  "rocky-spark": {
    name: "Rocky Spark",
    image: "/oddsparks/rocky-spark.png",
    wiki: `${wikiBase}Rocky_Spark`,
    group: "spark",
  },
  "scouty-spark": {
    name: "Scouty Spark",
    image: "/oddsparks/scouty-spark.png",
    wiki: `${wikiBase}Scouty_Spark`,
    group: "spark",
  },
  "scrubby-spark": {
    name: "Scrubby Spark",
    image: "/oddsparks/scrubby-spark.png",
    wiki: `${wikiBase}Scrubby_Spark`,
    group: "spark",
  },
  "slashy-spark": {
    name: "Slashy Spark",
    image: "/oddsparks/slashy-spark.png",
    wiki: `${wikiBase}Slashy_Spark`,
    group: "spark",
  },
  "stumpy-spark": {
    name: "Stumpy Spark",
    image: "/oddsparks/stumpy-spark.png",
    wiki: `${wikiBase}Stumpy_Spark`,
    group: "spark",
  },
};

export const workstations: Record<
  WorkstationId,
  { name: string; image?: string }
> = {
  "aetheric-distiller": { name: "Aetheric Distiller", image: "/oddsparks/aetheric-distiller.png" },
  "aetheric-distiller-shrine": { name: "Aetheric Distiller Shrine", image: "/oddsparks/aetheric-distiller-shrine.png" },
  "alchemy-lab": { name: "Alchemy Lab", image: "/oddsparks/alchemy-lab.png" },
  "arty-spark-shrine": { name: "Arty Spark Shrine", image: "/oddsparks/arty-spark-shrine.png" },
  "boomy-spark-shrine": { name: "Boomy Spark Shrine", image: "/oddsparks/boomy-spark-shrine.png" },
  "carry-spark-shrine": { name: "Carry Spark Shrine", image: "/oddsparks/carry-spark-shrine.png" },
  "choppy-spark-shrine": { name: "Choppy Spark Shrine", image: "/oddsparks/choppy-spark-shrine.png" },
  "crafty-spark-shrine": { name: "Crafty Spark Shrine", image: "/oddsparks/crafty-spark-shrine.png" },
  "crashy-spark-shrine": { name: "Crashy Spark Shrine", image: "/oddsparks/crashy-spark-shrine.png" },
  cutter: { name: "Cutter", image: "/oddsparks/cutter.png" },
  drill: { name: "Drill", image: "/oddsparks/drill.png" },
  "drilly-spark-shrine": { name: "Drilly Spark Shrine", image: "/oddsparks/drilly-spark-shrine.png" },
  furnace: { name: "Furnace", image: "/oddsparks/furnace.png" },
  greenhouse: { name: "Greenhouse" },
  "handy-spark-shrine": { name: "Handy Spark Shrine", image: "/oddsparks/handy-spark-shrine.png" },
  "hauling-spark-shrine": { name: "Hauling Spark Shrine", image: "/oddsparks/hauling-spark-shrine.png" },
  "loamy-spark-shrine": { name: "Loamy Spark Shrine", image: "/oddsparks/loamy-spark-shrine.png" },
  logger: { name: "Logger", image: "/oddsparks/logger.png" },
  loom: { name: "Loom", image: "/oddsparks/loom.png" },
  "miasma-collector": { name: "Miasma Collector", image: "/oddsparks/miasma-collector.png" },
  "plant-extractor": { name: "Plant Extractor", image: "/oddsparks/plant-extractor.png" },
  "puffy-spark-shrine": { name: "Puffy Spark Shrine", image: "/oddsparks/puffy-spark-shrine.png" },
  "rocky-spark-shrine": { name: "Rocky Spark Shrine", image: "/oddsparks/rocky-spark-shrine.png" },
  sawbench: { name: "Sawbench", image: "/oddsparks/sawbench.png" },
  "scouty-spark-shrine": { name: "Scouty Spark Shrine", image: "/oddsparks/scouty-spark-shrine.png" },
  "slashy-spark-shrine": { name: "Slashy Spark Shrine", image: "/oddsparks/slashy-spark-shrine.png" },
  "spark-workbench": { name: "Spark Workbench", image: "/oddsparks/spark-workbench.png" },
  "spark-workstation": { name: "Spark Workstation", image: "/oddsparks/spark-workstation.png" },
  "stone-workshop": { name: "Stone Workshop", image: "/oddsparks/stone-workshop.png" },
  stonecutter: { name: "Stonecutter", image: "/oddsparks/stonecutter.png" },
  "stumpy-spark-shrine": { name: "Stumpy Spark Shrine", image: "/oddsparks/stumpy-spark-shrine.png" },
  "wood-workshop": { name: "Wood Workshop", image: "/oddsparks/wood-workshop.png" },
  raw: { name: "Raw source" },
};

export const recipes: Recipe[] = [
  {
    id: "coal-furnace-coal-wood-fired-wooden-log-wooden-log",
    name: "Coal (Wood-fired)",
    product: "coal",
    productAmount: 1,
    workstation: "furnace",
    duration: 8,
    cyclesPerMinuteOneStumpy: 7.5,
    ingredients: [
      { item: "wooden-log", amount: 3 },
      { item: "wooden-log", perMinuteOneStumpy: 7.5 },
    ],
    wiki: "https://oddsparks.wiki.gg/wiki/Coal",
  },
  {
    id: "coal-furnace-coal-coal-fired-wooden-log-coal",
    name: "Coal (Coal-fired)",
    product: "coal",
    productAmount: 1,
    workstation: "furnace",
    duration: 8,
    cyclesPerMinuteOneStumpy: 7.5,
    ingredients: [
      { item: "wooden-log", amount: 3 },
      { item: "coal", perMinuteOneStumpy: 1.9 },
    ],
    wiki: "https://oddsparks.wiki.gg/wiki/Coal",
  },
  {
    id: "fabric-loom",
    name: "Fabric",
    product: "fabric",
    productAmount: 1,
    workstation: "loom",
    duration: 8,
    cyclesPerMinuteOneStumpy: 7.5,
    ingredients: [
      { item: "tree-bark", amount: 4 },
      { item: "rope", amount: 2 },
    ],
    wiki: "https://oddsparks.wiki.gg/wiki/Fabric",
  },
  {
    id: "fertiliser-cutter",
    name: "Fertiliser",
    product: "fertiliser",
    productAmount: 2,
    workstation: "cutter",
    duration: 24,
    cyclesPerMinuteOneStumpy: 2.5,
    ingredients: [{ item: "leaves", amount: 4 }],
    wiki: "https://oddsparks.wiki.gg/wiki/Fertiliser",
  },
  {
    id: "ladder-wood-workshop",
    name: "Ladder",
    product: "ladder",
    productAmount: 2,
    workstation: "wood-workshop",
    duration: 32,
    cyclesPerMinuteOneStumpy: 1.875,
    ingredients: [
      { item: "wooden-log", amount: 4 },
      { item: "sawn-timber", amount: 10 },
    ],
    wiki: "https://oddsparks.wiki.gg/wiki/Ladder",
  },
  {
    id: "leaves-logger-leaves-harvesting",
    name: "Leaves Harvesting",
    product: "leaves",
    productAmount: 1,
    workstation: "logger",
    duration: 2,
    cyclesPerMinuteOneStumpy: 30,
    ingredients: [],
    wiki: "https://oddsparks.wiki.gg/wiki/Leaves",
  },
  {
    id: "rope-loom",
    name: "Rope",
    product: "rope",
    productAmount: 1,
    workstation: "loom",
    duration: 16,
    cyclesPerMinuteOneStumpy: 3.75,
    ingredients: [
      { item: "leaves", amount: 2 },
      { item: "tree-bark", amount: 1 },
    ],
    wiki: "https://oddsparks.wiki.gg/wiki/Rope",
  },
  {
    id: "sawn-timber-sawbench",
    name: "Sawn Timber",
    product: "sawn-timber",
    productAmount: 1,
    workstation: "sawbench",
    duration: 16,
    cyclesPerMinuteOneStumpy: 3.75,
    ingredients: [{ item: "wooden-log", amount: 2 }],
    wiki: "https://oddsparks.wiki.gg/wiki/Sawn_Timber",
  },
  {
    id: "tree-bark-logger",
    name: "Tree Bark",
    product: "tree-bark",
    productAmount: 1,
    workstation: "logger",
    duration: 2,
    cyclesPerMinuteOneStumpy: 30,
    ingredients: [],
    wiki: "https://oddsparks.wiki.gg/wiki/Tree_Bark",
  },
  {
    id: "tree-bark-sawbench",
    name: "Tree Bark",
    product: "tree-bark",
    productAmount: 2,
    workstation: "sawbench",
    duration: 8,
    cyclesPerMinuteOneStumpy: 7.5,
    ingredients: [{ item: "wooden-log", amount: 1 }],
    wiki: "https://oddsparks.wiki.gg/wiki/Tree_Bark",
  },
  {
    id: "wooden-blade-wood-workshop",
    name: "Wooden Blade",
    product: "wooden-blade",
    productAmount: 1,
    workstation: "wood-workshop",
    duration: 48,
    cyclesPerMinuteOneStumpy: 1.25,
    ingredients: [
      { item: "sawn-timber", amount: 1 },
      { item: "wooden-panel", amount: 2 },
    ],
    wiki: "https://oddsparks.wiki.gg/wiki/Wooden_Blade",
  },
  {
    id: "wooden-log-logger-log-harvesting",
    name: "Log Harvesting",
    product: "wooden-log",
    productAmount: 1,
    workstation: "logger",
    duration: 2,
    cyclesPerMinuteOneStumpy: 30,
    ingredients: [],
    wiki: "https://oddsparks.wiki.gg/wiki/Wooden_Log",
  },
  {
    id: "wooden-panel-sawbench",
    name: "Wooden Panel",
    product: "wooden-panel",
    productAmount: 1,
    workstation: "sawbench",
    duration: 8,
    cyclesPerMinuteOneStumpy: 7.5,
    ingredients: [{ item: "sawn-timber", amount: 2 }],
    wiki: "https://oddsparks.wiki.gg/wiki/Wooden_Panel",
  },
  {
    id: "dowsing-stone-stone-workshop",
    name: "Dowsing Stone",
    product: "dowsing-stone",
    productAmount: 3,
    workstation: "stone-workshop",
    duration: 24,
    cyclesPerMinuteOneStumpy: 2.5,
    ingredients: [
      { item: "quartz", amount: 1 },
      { item: "rope", amount: 1 },
    ],
    wiki: "https://oddsparks.wiki.gg/wiki/Dowsing_Stone",
  },
  {
    id: "explosives-wood-workshop",
    name: "Explosives",
    product: "explosives",
    productAmount: 1,
    workstation: "wood-workshop",
    duration: 24,
    cyclesPerMinuteOneStumpy: 2.5,
    ingredients: [
      { item: "fertiliser", amount: 2 },
      { item: "limestone", amount: 4 },
    ],
    wiki: "https://oddsparks.wiki.gg/wiki/Explosives",
  },
  {
    id: "large-vial-furnace-big-vial-coal-fired-quartz-coal",
    name: "Big Vial (Coal-fired)",
    product: "large-vial",
    productAmount: 1,
    workstation: "furnace",
    duration: 128,
    cyclesPerMinuteOneStumpy: 0.46875,
    ingredients: [
      { item: "quartz", amount: 5 },
      { item: "coal", perMinuteOneStumpy: 1.9 },
    ],
    wiki: "https://oddsparks.wiki.gg/wiki/Large_Vial",
  },
  {
    id: "limestone-drill-limestone-harvesting",
    name: "Limestone Harvesting",
    product: "limestone",
    productAmount: 1,
    workstation: "drill",
    duration: 2,
    cyclesPerMinuteOneStumpy: 30,
    ingredients: [],
    wiki: "https://oddsparks.wiki.gg/wiki/Limestone",
  },
  {
    id: "limestone-stonecutter",
    name: "Limestone",
    product: "limestone",
    productAmount: 3,
    workstation: "stonecutter",
    duration: 16,
    cyclesPerMinuteOneStumpy: 3.75,
    ingredients: [{ item: "coral", amount: 4 }],
    wiki: "https://oddsparks.wiki.gg/wiki/Limestone",
  },
  {
    id: "path-tile-stone-workshop",
    name: "Path Tile",
    product: "path-tile",
    productAmount: 5,
    workstation: "stone-workshop",
    duration: 32,
    cyclesPerMinuteOneStumpy: 1.875,
    ingredients: [
      { item: "pebble", amount: 10 },
      { item: "limestone", amount: 5 },
    ],
    wiki: "https://oddsparks.wiki.gg/wiki/Path_Tile",
  },
  {
    id: "pebble-stonecutter",
    name: "Pebble",
    product: "pebble",
    productAmount: 2,
    workstation: "stonecutter",
    duration: 32,
    cyclesPerMinuteOneStumpy: 1.875,
    ingredients: [{ item: "stone", amount: 1 }],
    wiki: "https://oddsparks.wiki.gg/wiki/Pebble",
  },
  {
    id: "quartz-drill-quartz-harvesting",
    name: "Quartz Harvesting",
    product: "quartz",
    productAmount: 1,
    workstation: "drill",
    duration: 2,
    cyclesPerMinuteOneStumpy: 30,
    ingredients: [],
    wiki: "https://oddsparks.wiki.gg/wiki/Quartz",
  },
  {
    id: "small-vial-furnace-small-vial-wood-fired-quartz-wooden-log",
    name: "Small Vial (Wood-fired)",
    product: "small-vial",
    productAmount: 1,
    workstation: "furnace",
    duration: 32,
    cyclesPerMinuteOneStumpy: 1.875,
    ingredients: [
      { item: "quartz", amount: 2 },
      { item: "wooden-log", perMinuteOneStumpy: 7.5 },
    ],
    wiki: "https://oddsparks.wiki.gg/wiki/Small_Vial",
  },
  {
    id: "small-vial-furnace-small-vial-coal-fired-quartz-coal",
    name: "Small Vial (Coal-fired)",
    product: "small-vial",
    productAmount: 1,
    workstation: "furnace",
    duration: 32,
    cyclesPerMinuteOneStumpy: 1.875,
    ingredients: [
      { item: "quartz", amount: 2 },
      { item: "coal", perMinuteOneStumpy: 1.9 },
    ],
    wiki: "https://oddsparks.wiki.gg/wiki/Small_Vial",
  },
  {
    id: "stone-drill",
    name: "Stone",
    product: "stone",
    productAmount: 1,
    workstation: "drill",
    duration: 2,
    cyclesPerMinuteOneStumpy: 30,
    ingredients: [],
    wiki: "https://oddsparks.wiki.gg/wiki/Stone",
  },
  {
    id: "stone-plate-stonecutter",
    name: "Stone Plate",
    product: "stone-plate",
    productAmount: 1,
    workstation: "stonecutter",
    duration: 32,
    cyclesPerMinuteOneStumpy: 1.875,
    ingredients: [{ item: "stone", amount: 2 }],
    wiki: "https://oddsparks.wiki.gg/wiki/Stone_Plate",
  },
  {
    id: "stone-spike-stone-workshop",
    name: "Stone Spike",
    product: "stone-spike",
    productAmount: 4,
    workstation: "stone-workshop",
    duration: 16,
    cyclesPerMinuteOneStumpy: 3.75,
    ingredients: [
      { item: "wooden-blade", amount: 1 },
      { item: "stone-plate", amount: 4 },
    ],
    wiki: "https://oddsparks.wiki.gg/wiki/Stone_Spike",
  },
  {
    id: "stone-wheel-stone-workshop",
    name: "Stone Wheel",
    product: "stone-wheel",
    productAmount: 2,
    workstation: "stone-workshop",
    duration: 16,
    cyclesPerMinuteOneStumpy: 3.75,
    ingredients: [
      { item: "path-tile", amount: 4 },
      { item: "stone-plate", amount: 2 },
    ],
    wiki: "https://oddsparks.wiki.gg/wiki/Stone_Wheel",
  },
  {
    id: "aether-crystal-alchemy-lab",
    name: "Aether Crystal",
    product: "aether-crystal",
    productAmount: 10,
    workstation: "alchemy-lab",
    duration: 64,
    cyclesPerMinuteOneStumpy: 0.9,
    ingredients: [
      { item: "aether-seed", amount: 1 },
      { item: "raw-aether", amount: 1 },
    ],
    wiki: "https://oddsparks.wiki.gg/wiki/Aether_Crystal",
  },
  {
    id: "aether-shard-aetheric-distiller-pellet-refining",
    name: "Pellet Refining",
    product: "aether-shard",
    productAmount: 6,
    workstation: "aetheric-distiller",
    duration: 48,
    cyclesPerMinuteOneStumpy: 1.25,
    ingredients: [{ item: "aetheric-pellet", amount: 1 }],
    wiki: "https://oddsparks.wiki.gg/wiki/Aether_Shard",
  },
  {
    id: "aether-shard-aetheric-distiller-raw-distillation",
    name: "Raw Distillation",
    product: "aether-shard",
    productAmount: 6,
    workstation: "aetheric-distiller",
    duration: 48,
    cyclesPerMinuteOneStumpy: 1.25,
    ingredients: [{ item: "raw-aether", amount: 1 }],
    wiki: "https://oddsparks.wiki.gg/wiki/Aether_Shard",
  },
  {
    id: "aether-shard-aetheric-distiller-refined-distillation",
    name: "Refined Distillation",
    product: "aether-shard",
    productAmount: 30,
    workstation: "aetheric-distiller",
    duration: 128,
    cyclesPerMinuteOneStumpy: 0.46875,
    ingredients: [{ item: "refined-aether", amount: 1 }],
    wiki: "https://oddsparks.wiki.gg/wiki/Aether_Shard",
  },
  {
    id: "aether-shard-aetheric-distiller-shrine-pellet-refining",
    name: "Pellet Refining",
    product: "aether-shard",
    productAmount: 6,
    workstation: "aetheric-distiller-shrine",
    duration: 48,
    cyclesPerMinuteOneStumpy: 1.25,
    ingredients: [{ item: "aetheric-pellet", amount: 1 }],
    wiki: "https://oddsparks.wiki.gg/wiki/Aether_Shard",
  },
  {
    id: "aetheric-pellet-cutter-clump-dividing",
    name: "Clump Dividing",
    product: "aetheric-pellet",
    productAmount: 6,
    workstation: "cutter",
    duration: 128,
    cyclesPerMinuteOneStumpy: 0.46875,
    ingredients: [{ item: "aetheric-clump", amount: 1 }],
    wiki: "https://oddsparks.wiki.gg/wiki/Aetheric_Pellet",
  },
  {
    id: "miasma-vial-miasma-collector",
    name: "Miasma Vial",
    product: "miasma-vial",
    productAmount: 2,
    workstation: "miasma-collector",
    duration: 16,
    cyclesPerMinuteOneStumpy: 3.75,
    ingredients: [
      { item: "small-vial", amount: 2 },
      { item: "miasma", amount: 2 },
    ],
    wiki: "https://oddsparks.wiki.gg/wiki/Miasma_Vial",
  },
  {
    id: "raw-aether-alchemy-lab-miasma-transmutation",
    name: "Miasma Transmutation",
    product: "raw-aether",
    productAmount: 1,
    workstation: "alchemy-lab",
    duration: 48,
    cyclesPerMinuteOneStumpy: 1.25,
    ingredients: [
      { item: "miasma-vial", amount: 2 },
      { item: "aether-shard", amount: 1 },
    ],
    wiki: "https://oddsparks.wiki.gg/wiki/Raw_Aether",
  },
  {
    id: "refined-aether-alchemy-lab-aether-refinement",
    name: "Aether Refinement",
    product: "refined-aether",
    productAmount: 1,
    workstation: "alchemy-lab",
    duration: 64,
    cyclesPerMinuteOneStumpy: 0.9375,
    ingredients: [
      { item: "raw-aether", amount: 4 },
      { item: "large-vial", amount: 1 },
    ],
    wiki: "https://oddsparks.wiki.gg/wiki/Refined_Aether",
  },
  {
    id: "drill-bit-furnace-copper-ingot-coal",
    name: "Drill Bit",
    product: "drill-bit",
    productAmount: 1,
    workstation: "furnace",
    duration: 32,
    cyclesPerMinuteOneStumpy: 2,
    ingredients: [
      { item: "copper-ingot", amount: 2 },
      { item: "coal", perMinuteOneStumpy: 1.9 },
    ],
    wiki: "https://oddsparks.wiki.gg/wiki/Drill_Bit",
  },
  {
    id: "aether-flower-greenhouse",
    name: "Aether Flower",
    product: "aether-flower",
    productAmount: 0.1,
    workstation: "greenhouse",
    duration: 32,
    cyclesPerMinuteOneStumpy: 1.9,
    ingredients: [
      { item: "aetheric-pellet", amount: 2 },
      { item: "fertiliser", amount: 3 },
    ],
    wiki: "https://oddsparks.wiki.gg/wiki/Aether_Flower",
  },
  {
    id: "aether-seed-plant-extractor",
    name: "Aether Seed",
    product: "aether-seed",
    productAmount: 20,
    workstation: "plant-extractor",
    duration: 64,
    cyclesPerMinuteOneStumpy: 0.9,
    ingredients: [{ item: "aether-flower", amount: 1 }],
    wiki: "https://oddsparks.wiki.gg/wiki/Aether_Seed",
  },
  {
    id: "arty-spark-spark-workbench",
    name: "Arty Spark",
    product: "arty-spark",
    productAmount: 1,
    workstation: "spark-workbench",
    duration: 32,
    cyclesPerMinuteOneStumpy: 1.9,
    ingredients: [
      { item: "stumpy-spark", amount: 2 },
      { item: "rope", amount: 5 },
    ],
    wiki: "https://oddsparks.wiki.gg/wiki/Arty_Spark",
  },
  {
    id: "arty-spark-arty-spark-shrine",
    name: "Arty Spark",
    product: "arty-spark",
    productAmount: 1,
    workstation: "arty-spark-shrine",
    duration: 32,
    cyclesPerMinuteOneStumpy: 1.9,
    ingredients: [
      { item: "stumpy-spark", amount: 2 },
      { item: "rope", amount: 5 },
    ],
    wiki: "https://oddsparks.wiki.gg/wiki/Arty_Spark",
  },
  {
    id: "boomy-spark-spark-workstation",
    name: "Boomy Spark",
    product: "boomy-spark",
    productAmount: 3,
    workstation: "spark-workstation",
    duration: 48,
    cyclesPerMinuteOneStumpy: 1.25,
    ingredients: [
      { item: "rocky-spark", amount: 3 },
      { item: "explosives", amount: 5 },
    ],
    wiki: "https://oddsparks.wiki.gg/wiki/Boomy_Spark",
  },
  {
    id: "boomy-spark-boomy-spark-shrine",
    name: "Boomy Spark",
    product: "boomy-spark",
    productAmount: 3,
    workstation: "boomy-spark-shrine",
    duration: 48,
    cyclesPerMinuteOneStumpy: 1.25,
    ingredients: [
      { item: "rocky-spark", amount: 3 },
      { item: "explosives", amount: 5 },
    ],
    wiki: "https://oddsparks.wiki.gg/wiki/Boomy_Spark",
  },
  {
    id: "carry-spark-spark-workbench",
    name: "Carry Spark",
    product: "carry-spark",
    productAmount: 1,
    workstation: "spark-workbench",
    duration: 32,
    cyclesPerMinuteOneStumpy: 1.875,
    ingredients: [
      { item: "crafty-spark", amount: 1 },
      { item: "sawn-timber", amount: 4 },
    ],
    wiki: "https://oddsparks.wiki.gg/wiki/Carry_Spark",
  },
  {
    id: "carry-spark-carry-spark-shrine",
    name: "Carry Spark",
    product: "carry-spark",
    productAmount: 1,
    workstation: "carry-spark-shrine",
    duration: 32,
    cyclesPerMinuteOneStumpy: 1.875,
    ingredients: [
      { item: "crafty-spark", amount: 1 },
      { item: "sawn-timber", amount: 4 },
    ],
    wiki: "https://oddsparks.wiki.gg/wiki/Carry_Spark",
  },
  {
    id: "choppy-spark-spark-workbench",
    name: "Choppy Spark",
    product: "choppy-spark",
    productAmount: 1,
    workstation: "spark-workbench",
    duration: 64,
    cyclesPerMinuteOneStumpy: 0.938,
    ingredients: [
      { item: "stumpy-spark", amount: 3 },
      { item: "wooden-blade", amount: 1 },
    ],
    wiki: "https://oddsparks.wiki.gg/wiki/Choppy_Spark",
  },
  {
    id: "choppy-spark-choppy-spark-shrine",
    name: "Choppy Spark",
    product: "choppy-spark",
    productAmount: 1,
    workstation: "choppy-spark-shrine",
    duration: 64,
    cyclesPerMinuteOneStumpy: 0.938,
    ingredients: [
      { item: "stumpy-spark", amount: 3 },
      { item: "wooden-blade", amount: 1 },
    ],
    wiki: "https://oddsparks.wiki.gg/wiki/Choppy_Spark",
  },
  {
    id: "crafty-spark-spark-workbench",
    name: "Crafty Spark",
    product: "crafty-spark",
    productAmount: 1,
    workstation: "spark-workbench",
    duration: 48,
    cyclesPerMinuteOneStumpy: 1.25,
    ingredients: [
      { item: "stumpy-spark", amount: 2 },
      { item: "wooden-panel", amount: 2 },
    ],
    wiki: "https://oddsparks.wiki.gg/wiki/Crafty_Spark",
  },
  {
    id: "crafty-spark-crafty-spark-shrine",
    name: "Crafty Spark",
    product: "crafty-spark",
    productAmount: 1,
    workstation: "crafty-spark-shrine",
    duration: 48,
    cyclesPerMinuteOneStumpy: 1.25,
    ingredients: [
      { item: "stumpy-spark", amount: 2 },
      { item: "wooden-panel", amount: 2 },
    ],
    wiki: "https://oddsparks.wiki.gg/wiki/Crafty_Spark",
  },
  {
    id: "crashy-spark-spark-workstation",
    name: "Crashy Spark",
    product: "crashy-spark",
    productAmount: 1,
    workstation: "spark-workstation",
    duration: 64,
    cyclesPerMinuteOneStumpy: 0.938,
    ingredients: [
      { item: "boomy-spark", amount: 2 },
      { item: "stone-spike", amount: 7 },
    ],
    wiki: "https://oddsparks.wiki.gg/wiki/Crashy_Spark",
  },
  {
    id: "crashy-spark-crashy-spark-shrine",
    name: "Crashy Spark",
    product: "crashy-spark",
    productAmount: 1,
    workstation: "crashy-spark-shrine",
    duration: 64,
    cyclesPerMinuteOneStumpy: 0.938,
    ingredients: [
      { item: "boomy-spark", amount: 2 },
      { item: "stone-spike", amount: 7 },
    ],
    wiki: "https://oddsparks.wiki.gg/wiki/Crashy_Spark",
  },
  {
    id: "drilly-spark-drilly-spark-shrine",
    name: "Drilly Spark",
    product: "drilly-spark",
    productAmount: 1,
    workstation: "drilly-spark-shrine",
    duration: 64,
    cyclesPerMinuteOneStumpy: 0.938,
    ingredients: [
      { item: "slashy-spark", amount: 6 },
      { item: "drill-bit", amount: 3 },
    ],
    wiki: "https://oddsparks.wiki.gg/wiki/Drilly_Spark",
  },
  {
    id: "handy-spark-handy-spark-shrine",
    name: "Handy Spark",
    product: "handy-spark",
    productAmount: 1,
    workstation: "handy-spark-shrine",
    duration: 64,
    cyclesPerMinuteOneStumpy: 0.9,
    ingredients: [
      { item: "crafty-spark", amount: 5 },
      { item: "copper-ingot", amount: 4 },
      { item: "aether-crystal", amount: 1 },
    ],
    wiki: "https://oddsparks.wiki.gg/wiki/Handy_Spark",
  },
  {
    id: "hauling-spark-spark-workstation",
    name: "Hauling Spark",
    product: "hauling-spark",
    productAmount: 1,
    workstation: "spark-workstation",
    duration: 64,
    cyclesPerMinuteOneStumpy: 0.938,
    ingredients: [
      { item: "carry-spark", amount: 2 },
      { item: "stone-wheel", amount: 4 },
    ],
    wiki: "https://oddsparks.wiki.gg/wiki/Hauling_Spark",
  },
  {
    id: "hauling-spark-hauling-spark-shrine",
    name: "Hauling Spark",
    product: "hauling-spark",
    productAmount: 1,
    workstation: "hauling-spark-shrine",
    duration: 64,
    cyclesPerMinuteOneStumpy: 0.938,
    ingredients: [
      { item: "carry-spark", amount: 2 },
      { item: "stone-wheel", amount: 4 },
    ],
    wiki: "https://oddsparks.wiki.gg/wiki/Hauling_Spark",
  },
  {
    id: "loamy-spark-spark-workbench",
    name: "Loamy Spark",
    product: "loamy-spark",
    productAmount: 5,
    workstation: "spark-workbench",
    duration: 32,
    cyclesPerMinuteOneStumpy: 1.875,
    ingredients: [
      { item: "aether-shard", amount: 5 },
      { item: "fertiliser", amount: 3 },
    ],
    wiki: "https://oddsparks.wiki.gg/wiki/Loamy_Spark",
  },
  {
    id: "loamy-spark-loamy-spark-shrine",
    name: "Loamy Spark",
    product: "loamy-spark",
    productAmount: 5,
    workstation: "loamy-spark-shrine",
    duration: 32,
    cyclesPerMinuteOneStumpy: 1.875,
    ingredients: [
      { item: "aether-shard", amount: 5 },
      { item: "fertiliser", amount: 3 },
    ],
    wiki: "https://oddsparks.wiki.gg/wiki/Loamy_Spark",
  },
  {
    id: "puffy-spark-spark-workstation",
    name: "Puffy Spark",
    product: "puffy-spark",
    productAmount: 1,
    workstation: "spark-workstation",
    duration: 32,
    cyclesPerMinuteOneStumpy: 1.875,
    ingredients: [
      { item: "rocky-spark", amount: 1 },
      { item: "fabric", amount: 4 },
    ],
    wiki: "https://oddsparks.wiki.gg/wiki/Puffy_Spark",
  },
  {
    id: "puffy-spark-puffy-spark-shrine",
    name: "Puffy Spark",
    product: "puffy-spark",
    productAmount: 1,
    workstation: "puffy-spark-shrine",
    duration: 32,
    cyclesPerMinuteOneStumpy: 1.875,
    ingredients: [
      { item: "rocky-spark", amount: 1 },
      { item: "fabric", amount: 4 },
    ],
    wiki: "https://oddsparks.wiki.gg/wiki/Puffy_Spark",
  },
  {
    id: "rocky-spark-spark-workstation",
    name: "Rocky Spark",
    product: "rocky-spark",
    productAmount: 1,
    workstation: "spark-workstation",
    duration: 32,
    cyclesPerMinuteOneStumpy: 1.875,
    ingredients: [
      { item: "stumpy-spark", amount: 2 },
      { item: "stone", amount: 5 },
    ],
    wiki: "https://oddsparks.wiki.gg/wiki/Rocky_Spark",
  },
  {
    id: "rocky-spark-rocky-spark-shrine",
    name: "Rocky Spark",
    product: "rocky-spark",
    productAmount: 1,
    workstation: "rocky-spark-shrine",
    duration: 32,
    cyclesPerMinuteOneStumpy: 1.875,
    ingredients: [
      { item: "stumpy-spark", amount: 2 },
      { item: "stone", amount: 5 },
    ],
    wiki: "https://oddsparks.wiki.gg/wiki/Rocky_Spark",
  },
  {
    id: "scouty-spark-spark-workstation",
    name: "Scouty Spark",
    product: "scouty-spark",
    productAmount: 1,
    workstation: "spark-workstation",
    duration: 32,
    cyclesPerMinuteOneStumpy: 1.875,
    ingredients: [
      { item: "stumpy-spark", amount: 1 },
      { item: "dowsing-stone", amount: 1 },
    ],
    wiki: "https://oddsparks.wiki.gg/wiki/Scouty_Spark",
  },
  {
    id: "scouty-spark-scouty-spark-shrine",
    name: "Scouty Spark",
    product: "scouty-spark",
    productAmount: 1,
    workstation: "scouty-spark-shrine",
    duration: 32,
    cyclesPerMinuteOneStumpy: 1.875,
    ingredients: [
      { item: "stumpy-spark", amount: 1 },
      { item: "dowsing-stone", amount: 1 },
    ],
    wiki: "https://oddsparks.wiki.gg/wiki/Scouty_Spark",
  },
  {
    id: "slashy-spark-spark-workstation",
    name: "Slashy Spark",
    product: "slashy-spark",
    productAmount: 1,
    workstation: "spark-workstation",
    duration: 64,
    cyclesPerMinuteOneStumpy: 0.938,
    ingredients: [
      { item: "rocky-spark", amount: 2 },
      { item: "choppy-spark", amount: 3 },
    ],
    wiki: "https://oddsparks.wiki.gg/wiki/Slashy_Spark",
  },
  {
    id: "slashy-spark-slashy-spark-shrine",
    name: "Slashy Spark",
    product: "slashy-spark",
    productAmount: 1,
    workstation: "slashy-spark-shrine",
    duration: 64,
    cyclesPerMinuteOneStumpy: 0.938,
    ingredients: [
      { item: "rocky-spark", amount: 2 },
      { item: "choppy-spark", amount: 3 },
    ],
    wiki: "https://oddsparks.wiki.gg/wiki/Slashy_Spark",
  },
  {
    id: "stumpy-spark-spark-workbench",
    name: "Stumpy Spark",
    product: "stumpy-spark",
    productAmount: 1,
    workstation: "spark-workbench",
    duration: 32,
    cyclesPerMinuteOneStumpy: 1.875,
    ingredients: [
      { item: "aether-shard", amount: 1 },
      { item: "wooden-log", amount: 5 },
    ],
    wiki: "https://oddsparks.wiki.gg/wiki/Stumpy_Spark",
  },
  {
    id: "stumpy-spark-stumpy-spark-shrine",
    name: "Stumpy Spark",
    product: "stumpy-spark",
    productAmount: 1,
    workstation: "stumpy-spark-shrine",
    duration: 32,
    cyclesPerMinuteOneStumpy: 1.875,
    ingredients: [
      { item: "aether-shard", amount: 1 },
      { item: "wooden-log", amount: 5 },
    ],
    wiki: "https://oddsparks.wiki.gg/wiki/Stumpy_Spark",
  },
];

export const outputItems = recipes
  .map((recipe) => recipe.product)
  .filter((id, index, all) => all.indexOf(id) === index);

export const recipesByProduct = recipes.reduce(
  (accumulator, recipe) => {
    accumulator[recipe.product] = [...(accumulator[recipe.product] ?? []), recipe];
    return accumulator;
  },
  {} as Partial<Record<ItemId, Recipe[]>>,
);

export const defaultRecipeIdByProduct: Partial<Record<ItemId, string>> = {
  coal: "coal-furnace-coal-wood-fired-wooden-log-wooden-log",
  "tree-bark": "tree-bark-logger",
  "small-vial": "small-vial-furnace-small-vial-wood-fired-quartz-wooden-log",
  "aether-shard": "aether-shard-aetheric-distiller-pellet-refining",
  "arty-spark": "arty-spark-spark-workbench",
  "boomy-spark": "boomy-spark-spark-workstation",
  "carry-spark": "carry-spark-spark-workbench",
  "choppy-spark": "choppy-spark-spark-workbench",
  "crafty-spark": "crafty-spark-spark-workbench",
  "crashy-spark": "crashy-spark-spark-workstation",
  "hauling-spark": "hauling-spark-spark-workstation",
  "loamy-spark": "loamy-spark-spark-workbench",
  "puffy-spark": "puffy-spark-spark-workstation",
  "rocky-spark": "rocky-spark-spark-workstation",
  "scouty-spark": "scouty-spark-spark-workstation",
  "slashy-spark": "slashy-spark-spark-workstation",
  "stumpy-spark": "stumpy-spark-spark-workbench",
};

export const crewOptions = [
  {
    id: "stumpy-1",
    label: "1 Stumpy",
    multiplier: 1,
    sparks: ["stumpy-spark"] satisfies ItemId[],
  },
  {
    id: "stumpy-2",
    label: "2 Stumpy",
    multiplier: 2,
    sparks: ["stumpy-spark", "stumpy-spark"] satisfies ItemId[],
  },
  {
    id: "crafty-1",
    label: "1 Crafty",
    multiplier: 1.5,
    sparks: ["crafty-spark"] satisfies ItemId[],
  },
  {
    id: "crafty-2",
    label: "2 Crafty",
    multiplier: 3,
    sparks: ["crafty-spark", "crafty-spark"] satisfies ItemId[],
  },
  {
    id: "mixed-1-1",
    label: "1 Stumpy + 1 Crafty",
    multiplier: 2.5,
    sparks: ["stumpy-spark", "crafty-spark"] satisfies ItemId[],
  },
] as const;

export type CrewOptionId = (typeof crewOptions)[number]["id"];
