import packageJson from "../../package.json";
import type { ItemId, Language, Recipe, WorkstationId } from "./types";

export const uiText = {
  en: {
    activeTarget: "Current target",
    crewPerMachine: "Crew per machine",
    flow: "Flow",
    language: "Language",
    machineCount: "Machine count",
    machines: "Machines",
    output: "Output",
    perMachine: "per machine",
    rawDemand: "Raw demand",
    rawInputs: "Raw inputs",
    rawSource: "Raw source",
    recipeRules: "Recipe rules",
    sourcesInPlan: "Sources in plan",
    targetRate: "Target rate",
    wikiData: "Wiki data",
    with: "with",
    chooseItem: "Choose item",
    productionPlan: "Production plan",
  },
  de: {
    activeTarget: "Aktives Ziel",
    crewPerMachine: "Besetzung pro Maschine",
    flow: "Ablauf",
    language: "Sprache",
    machineCount: "Maschinenanzahl",
    machines: "Maschinen",
    output: "Output",
    perMachine: "je Maschine",
    rawDemand: "Rohbedarf",
    rawInputs: "Rohinputs",
    rawSource: "Quelle",
    recipeRules: "Rezeptregeln",
    sourcesInPlan: "Quellen im Plan",
    targetRate: "Zielrate",
    wikiData: "Wiki-Daten",
    with: "mit",
    chooseItem: "Item waehlen",
    productionPlan: "Produktionsplan",
  },
} satisfies Record<Language, Record<string, string>>;

export const appVersion = packageJson.version;

export const githubUrl = "https://github.com/sirkyomi/sparkulator";
const wikiBase = "https://oddsparks.wiki.gg/wiki/";

export const itemPhases = [
  { id: "woodland", label: "Woodland" },
  { id: "mountain", label: "Mountain" },
  { id: "metal", label: "Metal" },
] as const;

export type ItemPhaseId = (typeof itemPhases)[number]["id"];

export const items: Record<
  ItemId,
  { name: string; image: string; wiki: string; phase: ItemPhaseId }
> = {
  "arty-spark": {
    name: "Arty Spark",
    image: "/oddsparks/arty-spark.png",
    wiki: `${wikiBase}Arty_Spark`,
    phase: "woodland",
  },
  "carry-spark": {
    name: "Carry Spark",
    image: "/oddsparks/carry-spark.png",
    wiki: `${wikiBase}Carry_Spark`,
    phase: "woodland",
  },
  "choppy-spark": {
    name: "Choppy Spark",
    image: "/oddsparks/choppy-spark.png",
    wiki: `${wikiBase}Choppy_Spark`,
    phase: "woodland",
  },
  coal: {
    name: "Coal",
    image: "/oddsparks/coal.png",
    wiki: `${wikiBase}Coal`,
    phase: "woodland",
  },
  "crafty-spark": {
    name: "Crafty Spark",
    image: "/oddsparks/crafty-spark.png",
    wiki: `${wikiBase}Crafty_Spark`,
    phase: "woodland",
  },
  fabric: {
    name: "Fabric",
    image: "/oddsparks/fabric.png",
    wiki: `${wikiBase}Fabric`,
    phase: "woodland",
  },
  fertiliser: {
    name: "Fertiliser",
    image: "/oddsparks/fertiliser.png",
    wiki: `${wikiBase}Fertiliser`,
    phase: "woodland",
  },
  ladder: {
    name: "Ladder",
    image: "/oddsparks/ladder.png",
    wiki: `${wikiBase}Ladder`,
    phase: "woodland",
  },
  leaves: {
    name: "Leaves",
    image: "/oddsparks/leaves.png",
    wiki: `${wikiBase}Leaves`,
    phase: "woodland",
  },
  "loamy-spark": {
    name: "Loamy Spark",
    image: "/oddsparks/loamy-spark.png",
    wiki: `${wikiBase}Loamy_Spark`,
    phase: "woodland",
  },
  rope: {
    name: "Rope",
    image: "/oddsparks/rope.png",
    wiki: `${wikiBase}Rope`,
    phase: "woodland",
  },
  "sawn-timber": {
    name: "Sawn Timber",
    image: "/oddsparks/sawn-timber.png",
    wiki: `${wikiBase}Sawn_Timber`,
    phase: "woodland",
  },
  "stumpy-spark": {
    name: "Stumpy Spark",
    image: "/oddsparks/stumpy-spark.png",
    wiki: `${wikiBase}Stumpy_Spark`,
    phase: "woodland",
  },
  "tree-bark": {
    name: "Tree Bark",
    image: "/oddsparks/tree-bark.png",
    wiki: `${wikiBase}Tree_Bark`,
    phase: "woodland",
  },
  "wooden-blade": {
    name: "Wooden Blade",
    image: "/oddsparks/wooden-blade.png",
    wiki: `${wikiBase}Wooden_Blade`,
    phase: "woodland",
  },
  "wooden-log": {
    name: "Wooden Log",
    image: "/oddsparks/wooden-log.png",
    wiki: `${wikiBase}Wooden_Log`,
    phase: "woodland",
  },
  "wooden-panel": {
    name: "Wooden Panel",
    image: "/oddsparks/wooden-panel.png",
    wiki: `${wikiBase}Wooden_Panel`,
    phase: "woodland",
  },
  "big-vial": {
    name: "Big Vial",
    image: "/oddsparks/big-vial.png",
    wiki: `${wikiBase}Big_Vial`,
    phase: "mountain",
  },
  "boomy-spark": {
    name: "Boomy Spark",
    image: "/oddsparks/boomy-spark.png",
    wiki: `${wikiBase}Boomy_Spark`,
    phase: "mountain",
  },
  coral: {
    name: "Coral",
    image: "/oddsparks/coral.png",
    wiki: `${wikiBase}Coral`,
    phase: "mountain",
  },
  "crashy-spark": {
    name: "Crashy Spark",
    image: "/oddsparks/crashy-spark.png",
    wiki: `${wikiBase}Crashy_Spark`,
    phase: "mountain",
  },
  "dowsing-stone": {
    name: "Dowsing Stone",
    image: "/oddsparks/dowsing-stone.png",
    wiki: `${wikiBase}Dowsing_Stone`,
    phase: "mountain",
  },
  explosive: {
    name: "Explosive",
    image: "/oddsparks/explosive.png",
    wiki: `${wikiBase}Explosive`,
    phase: "mountain",
  },
  "fluted-coral": {
    name: "Fluted Coral",
    image: "/oddsparks/fluted-coral.png",
    wiki: `${wikiBase}Fluted_Coral`,
    phase: "mountain",
  },
  "gas-poison": {
    name: "Gas Poison",
    image: "/oddsparks/gas-poison.png",
    wiki: `${wikiBase}Gas_Poison`,
    phase: "mountain",
  },
  "hauling-spark": {
    name: "Hauling Spark",
    image: "/oddsparks/hauling-spark.png",
    wiki: `${wikiBase}Hauling_Spark`,
    phase: "mountain",
  },
  limestone: {
    name: "Limestone",
    image: "/oddsparks/limestone.png",
    wiki: `${wikiBase}Limestone`,
    phase: "mountain",
  },
  "miasma-vial": {
    name: "Miasma Vial",
    image: "/oddsparks/miasma-vial.png",
    wiki: `${wikiBase}Miasma_Vial`,
    phase: "mountain",
  },
  "path-tile": {
    name: "Path Tile",
    image: "/oddsparks/path-tile.png",
    wiki: `${wikiBase}Path_Tile`,
    phase: "mountain",
  },
  pebble: {
    name: "Pebble",
    image: "/oddsparks/pebble.png",
    wiki: `${wikiBase}Pebble`,
    phase: "mountain",
  },
  "puffy-spark": {
    name: "Puffy Spark",
    image: "/oddsparks/puffy-spark.png",
    wiki: `${wikiBase}Puffy_Spark`,
    phase: "mountain",
  },
  quartz: {
    name: "Quartz",
    image: "/oddsparks/quartz.png",
    wiki: `${wikiBase}Quartz`,
    phase: "mountain",
  },
  "raw-aether": {
    name: "Raw Aether",
    image: "/oddsparks/raw-aether.png",
    wiki: `${wikiBase}Raw_Aether`,
    phase: "mountain",
  },
  "refined-aether": {
    name: "Refined Aether",
    image: "/oddsparks/refined-aether.png",
    wiki: `${wikiBase}Refined_Aether`,
    phase: "mountain",
  },
  "rocky-spark": {
    name: "Rocky Spark",
    image: "/oddsparks/rocky-spark.png",
    wiki: `${wikiBase}Rocky_Spark`,
    phase: "mountain",
  },
  "scouty-spark": {
    name: "Scouty Spark",
    image: "/oddsparks/scouty-spark.png",
    wiki: `${wikiBase}Scouty_Spark`,
    phase: "mountain",
  },
  "slashy-spark": {
    name: "Slashy Spark",
    image: "/oddsparks/slashy-spark.png",
    wiki: `${wikiBase}Slashy_Spark`,
    phase: "mountain",
  },
  "small-vial": {
    name: "Small Vial",
    image: "/oddsparks/small-vial.png",
    wiki: `${wikiBase}Small_Vial`,
    phase: "mountain",
  },
  stone: {
    name: "Stone",
    image: "/oddsparks/stone.png",
    wiki: `${wikiBase}Stone`,
    phase: "mountain",
  },
  "stone-plate": {
    name: "Stone Plate",
    image: "/oddsparks/stone-plate.png",
    wiki: `${wikiBase}Stone_Plate`,
    phase: "mountain",
  },
  "stone-spike": {
    name: "Stone Spike",
    image: "/oddsparks/stone-spike.png",
    wiki: `${wikiBase}Stone_Spike`,
    phase: "mountain",
  },
  "stone-wheel": {
    name: "Stone Wheel",
    image: "/oddsparks/stone-wheel.png",
    wiki: `${wikiBase}Stone_Wheel`,
    phase: "mountain",
  },
  "aether-apple": {
    name: "Aether Apple",
    image: "/oddsparks/aether-apple.png",
    wiki: `${wikiBase}Aether_Apple`,
    phase: "metal",
  },
  "aether-crystal": {
    name: "Aether Crystal",
    image: "/oddsparks/aether-crystal.png",
    wiki: `${wikiBase}Aether_Crystal`,
    phase: "metal",
  },
  "aether-flower": {
    name: "Aether Flower",
    image: "/oddsparks/aether-flower.png",
    wiki: `${wikiBase}Aether_Flower`,
    phase: "metal",
  },
  "aether-seed": {
    name: "Aether Seed",
    image: "/oddsparks/aether-seed.png",
    wiki: `${wikiBase}Aether_Seed`,
    phase: "metal",
  },
  "aether-segment": {
    name: "Aether Segment",
    image: "/oddsparks/aether-segment.png",
    wiki: `${wikiBase}Aether_Segment`,
    phase: "metal",
  },
  "aether-shard": {
    name: "Aether Shard",
    image: "/oddsparks/aether-shard.png",
    wiki: `${wikiBase}Aether_Shard`,
    phase: "metal",
  },
  "aetheric-clump": {
    name: "Aetheric Clump",
    image: "/oddsparks/aetheric-clump.png",
    wiki: `${wikiBase}Aetheric_Clump`,
    phase: "metal",
  },
  "aetheric-pellet": {
    name: "Aetheric Pellet",
    image: "/oddsparks/aetheric-pellet.png",
    wiki: `${wikiBase}Aetheric_Pellet`,
    phase: "metal",
  },
  "beelephant-carapace": {
    name: "Beelephant Carapace",
    image: "/oddsparks/beelephant-carapace.png",
    wiki: `${wikiBase}Beelephant_Carapace`,
    phase: "metal",
  },
  "bumpy-geode": {
    name: "Bumpy Geode",
    image: "/oddsparks/bumpy-geode.png",
    wiki: `${wikiBase}Bumpy_Geode`,
    phase: "metal",
  },
  "burning-spark": {
    name: "Burning Spark",
    image: "/oddsparks/burning-spark.png",
    wiki: `${wikiBase}Burning_Spark`,
    phase: "metal",
  },
  clay: {
    name: "Clay",
    image: "/oddsparks/clay.png",
    wiki: `${wikiBase}Clay`,
    phase: "metal",
  },
  "cleansing-fragment": {
    name: "Cleansing Fragment",
    image: "/oddsparks/cleansing-fragment.png",
    wiki: `${wikiBase}Cleansing_Fragment`,
    phase: "metal",
  },
  "copper-cuttings": {
    name: "Copper Cuttings",
    image: "/oddsparks/copper-cuttings.png",
    wiki: `${wikiBase}Copper_Cuttings`,
    phase: "metal",
  },
  "copper-ingot": {
    name: "Copper Ingot",
    image: "/oddsparks/copper-ingot.png",
    wiki: `${wikiBase}Copper_Ingot`,
    phase: "metal",
  },
  "copper-ore": {
    name: "Copper Ore",
    image: "/oddsparks/copper-ore.png",
    wiki: `${wikiBase}Copper_Ore`,
    phase: "metal",
  },
  "copper-sap": {
    name: "Copper Sap",
    image: "/oddsparks/copper-sap.png",
    wiki: `${wikiBase}Copper_Sap`,
    phase: "metal",
  },
  "copper-seed": {
    name: "Copper Seed",
    image: "/oddsparks/copper-seed.png",
    wiki: `${wikiBase}Copper_Seed`,
    phase: "metal",
  },
  "coral-seed": {
    name: "Coral Seed",
    image: "/oddsparks/coral-seed.png",
    wiki: `${wikiBase}Coral_Seed`,
    phase: "metal",
  },
  "corrupted-aether": {
    name: "Corrupted Aether",
    image: "/oddsparks/corrupted-aether.png",
    wiki: `${wikiBase}Corrupted_Aether`,
    phase: "metal",
  },
  "corrupted-spark-token": {
    name: "Corrupted Spark Token",
    image: "/oddsparks/corrupted-spark-token.png",
    wiki: `${wikiBase}Corrupted_Spark_Token`,
    phase: "metal",
  },
  "cracked-geode": {
    name: "Cracked Geode",
    image: "/oddsparks/cracked-geode.png",
    wiki: `${wikiBase}Cracked_Geode`,
    phase: "metal",
  },
  "crangolin-lavascale": {
    name: "Crangolin Lavascale",
    image: "/oddsparks/crangolin-lavascale.png",
    wiki: `${wikiBase}Crangolin_Lavascale`,
    phase: "metal",
  },
  "crangolin-scale": {
    name: "Crangolin Scale",
    image: "/oddsparks/crangolin-scale.png",
    wiki: `${wikiBase}Crangolin_Scale`,
    phase: "metal",
  },
  "drill-bit": {
    name: "Drill Bit",
    image: "/oddsparks/drill-bit.png",
    wiki: `${wikiBase}Drill_Bit`,
    phase: "metal",
  },
  "drilly-spark": {
    name: "Drilly Spark",
    image: "/oddsparks/drilly-spark.png",
    wiki: `${wikiBase}Drilly_Spark`,
    phase: "metal",
  },
  "fireshroom-cluster": {
    name: "Fireshroom Cluster",
    image: "/oddsparks/fireshroom-cluster.png",
    wiki: `${wikiBase}Fireshroom_Cluster`,
    phase: "metal",
  },
  fog: {
    name: "Fog",
    image: "/oddsparks/fog.png",
    wiki: `${wikiBase}Fog`,
    phase: "metal",
  },
  "freezing-spark": {
    name: "Freezing Spark",
    image: "/oddsparks/freezing-spark.png",
    wiki: `${wikiBase}Freezing_Spark`,
    phase: "metal",
  },
  "frilled-walrion-tusk": {
    name: "Frilled Walrion Tusk",
    image: "/oddsparks/frilled-walrion-tusk.png",
    wiki: `${wikiBase}Frilled_Walrion_Tusk`,
    phase: "metal",
  },
  frost: {
    name: "Frost",
    image: "/oddsparks/frost.png",
    wiki: `${wikiBase}Frost`,
    phase: "metal",
  },
  "frowl-sac": {
    name: "Frowl Sac",
    image: "/oddsparks/frowl-sac.png",
    wiki: `${wikiBase}Frowl_Sac`,
    phase: "metal",
  },
  "frozen-log": {
    name: "Frozen Log",
    image: "/oddsparks/frozen-log.png",
    wiki: `${wikiBase}Frozen_Log`,
    phase: "metal",
  },
  "frozen-stone": {
    name: "Frozen Stone",
    image: "/oddsparks/frozen-stone.png",
    wiki: `${wikiBase}Frozen_Stone`,
    phase: "metal",
  },
  "geode-cluster": {
    name: "Geode Cluster",
    image: "/oddsparks/geode-cluster.png",
    wiki: `${wikiBase}Geode_Cluster`,
    phase: "metal",
  },
  glowshroom: {
    name: "Glowshroom",
    image: "/oddsparks/glowshroom.png",
    wiki: `${wikiBase}Glowshroom`,
    phase: "metal",
  },
  "grey-aether": {
    name: "Grey Aether",
    image: "/oddsparks/grey-aether.png",
    wiki: `${wikiBase}Grey_Aether`,
    phase: "metal",
  },
  "handy-spark": {
    name: "Handy Spark",
    image: "/oddsparks/handy-spark.png",
    wiki: `${wikiBase}Handy_Spark`,
    phase: "metal",
  },
  "icehorn-ram-horn": {
    name: "Icehorn Ram Horn",
    image: "/oddsparks/icehorn-ram-horn.png",
    wiki: `${wikiBase}Icehorn_Ram_Horn`,
    phase: "metal",
  },
  "lava-cap": {
    name: "Lava Cap",
    image: "/oddsparks/lava-cap.png",
    wiki: `${wikiBase}Lava_Cap`,
    phase: "metal",
  },
  "lava-shellhorse-comb": {
    name: "Lava Shellhorse Comb",
    image: "/oddsparks/lava-shellhorse-comb.png",
    wiki: `${wikiBase}Lava_Shellhorse_Comb`,
    phase: "metal",
  },
  "leaf-knot": {
    name: "Leaf Knot",
    image: "/oddsparks/leaf-knot.png",
    wiki: `${wikiBase}Leaf_Knot`,
    phase: "metal",
  },
  "liquid-fertiliser": {
    name: "Liquid Fertiliser",
    image: "/oddsparks/liquid-fertiliser.png",
    wiki: `${wikiBase}Liquid_Fertiliser`,
    phase: "metal",
  },
  "liquid-fertilizer": {
    name: "Liquid Fertilizer",
    image: "/oddsparks/liquid-fertilizer.png",
    wiki: `${wikiBase}Liquid_Fertilizer`,
    phase: "metal",
  },
  "mantis-stag-antler": {
    name: "Mantis Stag Antler",
    image: "/oddsparks/mantis-stag-antler.png",
    wiki: `${wikiBase}Mantis_Stag_Antler`,
    phase: "metal",
  },
  miasma: {
    name: "Miasma",
    image: "/oddsparks/miasma.png",
    wiki: `${wikiBase}Miasma`,
    phase: "metal",
  },
  "pengus-tendon": {
    name: "Pengus Tendon",
    image: "/oddsparks/pengus-tendon.png",
    wiki: `${wikiBase}Pengus_Tendon`,
    phase: "metal",
  },
  "rock-teron-shell": {
    name: "Rock Teron Shell",
    image: "/oddsparks/rock-teron-shell.png",
    wiki: `${wikiBase}Rock_Teron_Shell`,
    phase: "metal",
  },
  "scrubby-spark": {
    name: "Scrubby Spark",
    image: "/oddsparks/scrubby-spark.png",
    wiki: `${wikiBase}Scrubby_Spark`,
    phase: "metal",
  },
  "shiny-geode": {
    name: "Shiny Geode",
    image: "/oddsparks/shiny-geode.png",
    wiki: `${wikiBase}Shiny_Geode`,
    phase: "metal",
  },
  sponge: {
    name: "Sponge",
    image: "/oddsparks/sponge.png",
    wiki: `${wikiBase}Sponge`,
    phase: "metal",
  },
  "squilican-tube": {
    name: "Squilican Tube",
    image: "/oddsparks/squilican-tube.png",
    wiki: `${wikiBase}Squilican_Tube`,
    phase: "metal",
  },
  "stellar-fertiliser": {
    name: "Stellar Fertiliser",
    image: "/oddsparks/stellar-fertiliser.png",
    wiki: `${wikiBase}Stellar_Fertiliser`,
    phase: "metal",
  },
  "stellar-fertilizer": {
    name: "Stellar Fertilizer",
    image: "/oddsparks/stellar-fertilizer.png",
    wiki: `${wikiBase}Stellar_Fertilizer`,
    phase: "metal",
  },
  "stellar-ice": {
    name: "Stellar Ice",
    image: "/oddsparks/stellar-ice.png",
    wiki: `${wikiBase}Stellar_Ice`,
    phase: "metal",
  },
  "stellar-leaves": {
    name: "Stellar Leaves",
    image: "/oddsparks/stellar-leaves.png",
    wiki: `${wikiBase}Stellar_Leaves`,
    phase: "metal",
  },
  "stellar-seed": {
    name: "Stellar Seed",
    image: "/oddsparks/stellar-seed.png",
    wiki: `${wikiBase}Stellar_Seed`,
    phase: "metal",
  },
  "stone-block": {
    name: "Stone Block",
    image: "/oddsparks/stone-block.png",
    wiki: `${wikiBase}Stone_Block`,
    phase: "metal",
  },
  "volcanic-soil": {
    name: "Volcanic Soil",
    image: "/oddsparks/volcanic-soil.png",
    wiki: `${wikiBase}Volcanic_Soil`,
    phase: "metal",
  },
};

export const workstations: Record<
  WorkstationId,
  { name: string; image?: string }
> = {
  raw: { name: "Raw source" },
  logger: { name: "Logger", image: "/oddsparks/logger.png" },
  sawbench: { name: "Sawbench", image: "/oddsparks/sawbench.png" },
  loom: { name: "Loom", image: "/oddsparks/loom.png" },
  cutter: { name: "Cutter", image: "/oddsparks/cutter.png" },
  "wood-workshop": { name: "Wood Workshop", image: "/oddsparks/wood-workshop.png" },
  furnace: { name: "Furnace", image: "/oddsparks/furnace.png" },
  drill: { name: "Drill", image: "/oddsparks/drill.png" },
  "ore-miner": { name: "Ore Miner", image: "/oddsparks/ore-miner.png" },
  stonecutter: { name: "Stonecutter", image: "/oddsparks/stonecutter.png" },
  "stone-workshop": { name: "Stone Workshop", image: "/oddsparks/stone-workshop.png" },
  "spark-workbench": { name: "Spark Workbench", image: "/oddsparks/spark-workbench.png" },
  "spark-workstation": { name: "Spark Workstation", image: "/oddsparks/spark-workstation.png" },
  "metal-spark-workstation": { name: "Metal Spark Workstation", image: "/oddsparks/metal-spark-workstation.png" },
  "alchemy-station": { name: "Alchemy Station", image: "/oddsparks/alchemy-station.png" },
  "aetheric-collider": { name: "Aetheric Collider", image: "/oddsparks/aetheric-collider.png" },
  extractor: { name: "Extractor", image: "/oddsparks/extractor.png" },
  "plant-extractor": { name: "Plant Extractor", image: "/oddsparks/plant-extractor.png" },
  "geode-breaker": { name: "Geode Breaker", image: "/oddsparks/geode-breaker.png" },
  compressor: { name: "Compressor", image: "/oddsparks/compressor.png" },
  "clay-digger": { name: "Clay Digger", image: "/oddsparks/clay-digger.png" },
};

export const recipes: Recipe[] = [
  {
    id: "aetheric-clump-aether-clump-fusion-1-leaf-knot-1-refined-aether",
    name: "Aether Clump Fusion",
    product: "aetheric-clump",
    productAmount: 2,
    workstation: "aetheric-collider",
    duration: 60,
    cyclesPerMinuteOneStumpy: 1,
    ingredients: [
      { item: "leaf-knot", amount: 1 },
      { item: "refined-aether", amount: 1 },
    ],
    wiki: "https://oddsparks.wiki.gg/wiki/Aetheric_Clump",
  },
  {
    id: "aetheric-pellet-clump-dividing-1-aetheric-clump",
    name: "Clump Dividing",
    product: "aetheric-pellet",
    productAmount: 6,
    workstation: "aetheric-collider",
    duration: 128,
    cyclesPerMinuteOneStumpy: 0.46875,
    ingredients: [{ item: "aetheric-clump", amount: 1 }],
    wiki: "https://oddsparks.wiki.gg/wiki/Aetheric_Pellet",
  },
  {
    id: "aether-shard-aether-shard-raw",
    name: "Aether Shard",
    product: "aether-shard",
    productAmount: 1,
    workstation: "raw",
    duration: 0,
    cyclesPerMinuteOneStumpy: 1,
    ingredients: [],
    wiki: "https://oddsparks.wiki.gg/wiki/Aether_Shard",
  },
  {
    id: "aether-shard-pellet-refining-1-aetheric-pellet",
    name: "Pellet Refining",
    product: "aether-shard",
    productAmount: 6,
    workstation: "aetheric-collider",
    duration: 48,
    cyclesPerMinuteOneStumpy: 1.25,
    ingredients: [{ item: "aetheric-pellet", amount: 1 }],
    wiki: "https://oddsparks.wiki.gg/wiki/Aether_Shard",
  },
  {
    id: "aetheric-pellet-aether-pellet-fusion-1-leaf-knot-1-raw-aether",
    name: "Aether Pellet Fusion",
    product: "aetheric-pellet",
    productAmount: 2,
    workstation: "aetheric-collider",
    duration: 60,
    cyclesPerMinuteOneStumpy: 1,
    ingredients: [
      { item: "leaf-knot", amount: 1 },
      { item: "raw-aether", amount: 1 },
    ],
    wiki: "https://oddsparks.wiki.gg/wiki/Aetheric_Pellet",
  },
  {
    id: "aether-crystal-aether-seed-crystallisation-1-aether-seed-1-raw-aether",
    name: "Aether Seed Crystallisation",
    product: "aether-crystal",
    productAmount: 10,
    workstation: "alchemy-station",
    duration: 64,
    cyclesPerMinuteOneStumpy: 0.9,
    ingredients: [
      { item: "aether-seed", amount: 1 },
      { item: "raw-aether", amount: 1 },
    ],
    wiki: "https://oddsparks.wiki.gg/wiki/Aether_Crystal",
  },
  {
    id: "tree-bark-bark-1-wooden-log",
    name: "Bark",
    product: "tree-bark",
    productAmount: 2,
    workstation: "sawbench",
    duration: 8,
    cyclesPerMinuteOneStumpy: 7.5,
    ingredients: [{ item: "wooden-log", amount: 1 }],
    wiki: "https://oddsparks.wiki.gg/wiki/Tree_Bark",
  },
  {
    id: "grey-aether-spark-token-cleansing-1-corrupted-spark-token-2-cleansing-fragment",
    name: "Spark Token Cleansing",
    product: "grey-aether",
    productAmount: 5,
    workstation: "alchemy-station",
    duration: 60,
    cyclesPerMinuteOneStumpy: 1,
    ingredients: [
      { item: "corrupted-spark-token", amount: 1 },
      { item: "cleansing-fragment", amount: 2 },
    ],
    wiki: "https://oddsparks.wiki.gg/wiki/Grey_Aether",
  },
  {
    id: "scrubby-spark-spark-token-cleansing-1-corrupted-spark-token-2-cleansing-fragment",
    name: "Spark Token Cleansing",
    product: "scrubby-spark",
    productAmount: 1,
    workstation: "metal-spark-workstation",
    duration: 60,
    cyclesPerMinuteOneStumpy: 1,
    ingredients: [
      { item: "corrupted-spark-token", amount: 1 },
      { item: "cleansing-fragment", amount: 2 },
    ],
    wiki: "https://oddsparks.wiki.gg/wiki/Scrubby_Spark",
  },
  {
    id: "cleansing-fragment-cleansing-fragment-enrichment-4-grey-aether-18-cleansing-fragment",
    name: "Cleansing Fragment Enrichment",
    product: "cleansing-fragment",
    productAmount: 20,
    workstation: "alchemy-station",
    duration: 60,
    cyclesPerMinuteOneStumpy: 1,
    ingredients: [
      { item: "grey-aether", amount: 4 },
      { item: "cleansing-fragment", amount: 18 },
    ],
    wiki: "https://oddsparks.wiki.gg/wiki/Cleansing_Fragment",
  },
  {
    id: "raw-aether-corrupted-aether-cleansing-2-corrupted-aether-1-cleansing-fragment",
    name: "Corrupted Aether Cleansing",
    product: "raw-aether",
    productAmount: 8,
    workstation: "alchemy-station",
    duration: 60,
    cyclesPerMinuteOneStumpy: 1,
    ingredients: [
      { item: "corrupted-aether", amount: 2 },
      { item: "cleansing-fragment", amount: 1 },
    ],
    wiki: "https://oddsparks.wiki.gg/wiki/Raw_Aether",
  },
  {
    id: "aetheric-clump-corrupted-aether-cleansing-2-corrupted-aether-1-cleansing-fragment",
    name: "Corrupted Aether Cleansing",
    product: "aetheric-clump",
    productAmount: 1,
    workstation: "alchemy-station",
    duration: 60,
    cyclesPerMinuteOneStumpy: 1,
    ingredients: [
      { item: "corrupted-aether", amount: 2 },
      { item: "cleansing-fragment", amount: 1 },
    ],
    wiki: "https://oddsparks.wiki.gg/wiki/Aetheric_Clump",
  },
  {
    id: "raw-aether-grey-aether-purification-2-grey-aether-5-aether-seed",
    name: "Grey Aether Purification",
    product: "raw-aether",
    productAmount: 8,
    workstation: "alchemy-station",
    duration: 60,
    cyclesPerMinuteOneStumpy: 1,
    ingredients: [
      { item: "grey-aether", amount: 2 },
      { item: "aether-seed", amount: 5 },
    ],
    wiki: "https://oddsparks.wiki.gg/wiki/Raw_Aether",
  },
  {
    id: "aetheric-clump-grey-aether-purification-2-grey-aether-5-aether-seed",
    name: "Grey Aether Purification",
    product: "aetheric-clump",
    productAmount: 1,
    workstation: "alchemy-station",
    duration: 60,
    cyclesPerMinuteOneStumpy: 1,
    ingredients: [
      { item: "grey-aether", amount: 2 },
      { item: "aether-seed", amount: 5 },
    ],
    wiki: "https://oddsparks.wiki.gg/wiki/Aetheric_Clump",
  },
  {
    id: "copper-ingot-copper-ore-smelting-3-copper-ore",
    name: "Copper Ore Smelting",
    product: "copper-ingot",
    productAmount: 1,
    workstation: "furnace",
    duration: 60,
    cyclesPerMinuteOneStumpy: 1,
    ingredients: [{ item: "copper-ore", amount: 3 }],
    wiki: "https://oddsparks.wiki.gg/wiki/Copper_Ingot",
  },
  {
    id: "copper-ingot-copper-sap-smelting-1-copper-sap",
    name: "Copper Sap Smelting",
    product: "copper-ingot",
    productAmount: 1,
    workstation: "furnace",
    duration: 60,
    cyclesPerMinuteOneStumpy: 1,
    ingredients: [{ item: "copper-sap", amount: 1 }],
    wiki: "https://oddsparks.wiki.gg/wiki/Copper_Ingot",
  },
  {
    id: "copper-seed-copper-sap-beading-1-copper-sap",
    name: "Copper Sap Beading",
    product: "copper-seed",
    productAmount: 8,
    workstation: "compressor",
    duration: 60,
    cyclesPerMinuteOneStumpy: 1,
    ingredients: [{ item: "copper-sap", amount: 1 }],
    wiki: "https://oddsparks.wiki.gg/wiki/Copper_Seed",
  },
  {
    id: "copper-ingot-copper-seed-smelting-3-copper-seed",
    name: "Copper Seed Smelting",
    product: "copper-ingot",
    productAmount: 1,
    workstation: "furnace",
    duration: 60,
    cyclesPerMinuteOneStumpy: 1,
    ingredients: [{ item: "copper-seed", amount: 3 }],
    wiki: "https://oddsparks.wiki.gg/wiki/Copper_Ingot",
  },
  {
    id: "coral-coral-1-fluted-coral",
    name: "Coral",
    product: "coral",
    productAmount: 8,
    workstation: "compressor",
    duration: 60,
    cyclesPerMinuteOneStumpy: 1,
    ingredients: [{ item: "fluted-coral", amount: 1 }],
    wiki: "https://oddsparks.wiki.gg/wiki/Coral",
  },
  {
    id: "volcanic-soil-break-bumpy-geode-1-bumpy-geode",
    name: "Break Bumpy Geode",
    product: "volcanic-soil",
    productAmount: 20,
    workstation: "geode-breaker",
    duration: 60,
    cyclesPerMinuteOneStumpy: 1,
    ingredients: [{ item: "bumpy-geode", amount: 1 }],
    wiki: "https://oddsparks.wiki.gg/wiki/Volcanic_Soil",
  },
  {
    id: "coal-break-bumpy-geode-1-bumpy-geode",
    name: "Break Bumpy Geode",
    product: "coal",
    productAmount: 10,
    workstation: "furnace",
    duration: 60,
    cyclesPerMinuteOneStumpy: 1,
    ingredients: [{ item: "bumpy-geode", amount: 1 }],
    wiki: "https://oddsparks.wiki.gg/wiki/Coal",
  },
  {
    id: "glowshroom-break-bumpy-geode-1-bumpy-geode",
    name: "Break Bumpy Geode",
    product: "glowshroom",
    productAmount: 10,
    workstation: "geode-breaker",
    duration: 60,
    cyclesPerMinuteOneStumpy: 1,
    ingredients: [{ item: "bumpy-geode", amount: 1 }],
    wiki: "https://oddsparks.wiki.gg/wiki/Glowshroom",
  },
  {
    id: "bumpy-geode-break-geode-cluster-1-geode-cluster",
    name: "Break Geode Cluster",
    product: "bumpy-geode",
    productAmount: 10,
    workstation: "geode-breaker",
    duration: 60,
    cyclesPerMinuteOneStumpy: 1,
    ingredients: [{ item: "geode-cluster", amount: 1 }],
    wiki: "https://oddsparks.wiki.gg/wiki/Bumpy_Geode",
  },
  {
    id: "shiny-geode-break-geode-cluster-1-geode-cluster",
    name: "Break Geode Cluster",
    product: "shiny-geode",
    productAmount: 10,
    workstation: "geode-breaker",
    duration: 60,
    cyclesPerMinuteOneStumpy: 1,
    ingredients: [{ item: "geode-cluster", amount: 1 }],
    wiki: "https://oddsparks.wiki.gg/wiki/Shiny_Geode",
  },
  {
    id: "cracked-geode-break-geode-cluster-1-geode-cluster",
    name: "Break Geode Cluster",
    product: "cracked-geode",
    productAmount: 10,
    workstation: "geode-breaker",
    duration: 60,
    cyclesPerMinuteOneStumpy: 1,
    ingredients: [{ item: "geode-cluster", amount: 1 }],
    wiki: "https://oddsparks.wiki.gg/wiki/Cracked_Geode",
  },
  {
    id: "volcanic-soil-break-shiny-geode-1-shiny-geode",
    name: "Break Shiny Geode",
    product: "volcanic-soil",
    productAmount: 20,
    workstation: "geode-breaker",
    duration: 60,
    cyclesPerMinuteOneStumpy: 1,
    ingredients: [{ item: "shiny-geode", amount: 1 }],
    wiki: "https://oddsparks.wiki.gg/wiki/Volcanic_Soil",
  },
  {
    id: "copper-ore-break-shiny-geode-1-shiny-geode",
    name: "Break Shiny Geode",
    product: "copper-ore",
    productAmount: 10,
    workstation: "geode-breaker",
    duration: 60,
    cyclesPerMinuteOneStumpy: 1,
    ingredients: [{ item: "shiny-geode", amount: 1 }],
    wiki: "https://oddsparks.wiki.gg/wiki/Copper_Ore",
  },
  {
    id: "glowshroom-break-shiny-geode-1-shiny-geode",
    name: "Break Shiny Geode",
    product: "glowshroom",
    productAmount: 10,
    workstation: "geode-breaker",
    duration: 60,
    cyclesPerMinuteOneStumpy: 1,
    ingredients: [{ item: "shiny-geode", amount: 1 }],
    wiki: "https://oddsparks.wiki.gg/wiki/Glowshroom",
  },
  {
    id: "volcanic-soil-break-cracked-geode-1-cracked-geode",
    name: "Break Cracked Geode",
    product: "volcanic-soil",
    productAmount: 20,
    workstation: "geode-breaker",
    duration: 60,
    cyclesPerMinuteOneStumpy: 1,
    ingredients: [{ item: "cracked-geode", amount: 1 }],
    wiki: "https://oddsparks.wiki.gg/wiki/Volcanic_Soil",
  },
  {
    id: "copper-ore-break-cracked-geode-1-cracked-geode",
    name: "Break Cracked Geode",
    product: "copper-ore",
    productAmount: 10,
    workstation: "geode-breaker",
    duration: 60,
    cyclesPerMinuteOneStumpy: 1,
    ingredients: [{ item: "cracked-geode", amount: 1 }],
    wiki: "https://oddsparks.wiki.gg/wiki/Copper_Ore",
  },
  {
    id: "coal-break-cracked-geode-1-cracked-geode",
    name: "Break Cracked Geode",
    product: "coal",
    productAmount: 10,
    workstation: "furnace",
    duration: 60,
    cyclesPerMinuteOneStumpy: 1,
    ingredients: [{ item: "cracked-geode", amount: 1 }],
    wiki: "https://oddsparks.wiki.gg/wiki/Coal",
  },
  {
    id: "grey-aether-corrupted-aether-purification-1-corrupted-aether-1-aether-crystal",
    name: "Corrupted Aether Purification",
    product: "grey-aether",
    productAmount: 1,
    workstation: "alchemy-station",
    duration: 60,
    cyclesPerMinuteOneStumpy: 1,
    ingredients: [
      { item: "corrupted-aether", amount: 1 },
      { item: "aether-crystal", amount: 1 },
    ],
    wiki: "https://oddsparks.wiki.gg/wiki/Grey_Aether",
  },
  {
    id: "cleansing-fragment-corrupted-aether-purification-1-corrupted-aether-1-aether-crystal",
    name: "Corrupted Aether Purification",
    product: "cleansing-fragment",
    productAmount: 1,
    workstation: "alchemy-station",
    duration: 60,
    cyclesPerMinuteOneStumpy: 1,
    ingredients: [
      { item: "corrupted-aether", amount: 1 },
      { item: "aether-crystal", amount: 1 },
    ],
    wiki: "https://oddsparks.wiki.gg/wiki/Cleansing_Fragment",
  },
  {
    id: "cleansing-fragment-cleansing-fragment-enrichment-raw",
    name: "Cleansing Fragment Enrichment",
    product: "cleansing-fragment",
    productAmount: 1,
    workstation: "raw",
    duration: 60,
    cyclesPerMinuteOneStumpy: 1,
    ingredients: [],
    wiki: "https://oddsparks.wiki.gg/wiki/Cleansing_Fragment",
  },
  {
    id: "dowsing-stone-dowsing-stone-1-quartz-1-rope",
    name: "Dowsing Stone",
    product: "dowsing-stone",
    productAmount: 3,
    workstation: "stone-workshop",
    duration: 24,
    cyclesPerMinuteOneStumpy: 2.5,
    ingredients: [
      { item: "quartz", amount: 1 },
      { item: "rope", amount: 1 },
    ],
    wiki: "https://oddsparks.wiki.gg/wiki/Dowsing_Stone",
  },
  {
    id: "drill-bit-drill-bit-2-copper-ingot",
    name: "Drill Bit",
    product: "drill-bit",
    productAmount: 2,
    workstation: "furnace",
    duration: 60,
    cyclesPerMinuteOneStumpy: 1,
    ingredients: [{ item: "copper-ingot", amount: 2 }],
    wiki: "https://oddsparks.wiki.gg/wiki/Drill_Bit",
  },
  {
    id: "explosive-explosives-2-fertiliser-4-limestone",
    name: "Explosives",
    product: "explosive",
    productAmount: 1,
    workstation: "wood-workshop",
    duration: 24,
    cyclesPerMinuteOneStumpy: 2.5,
    ingredients: [
      { item: "fertiliser", amount: 2 },
      { item: "limestone", amount: 4 },
    ],
    wiki: "https://oddsparks.wiki.gg/wiki/Explosive",
  },
  {
    id: "aether-seed-extract-aether-apple-1-aether-apple",
    name: "Extract Aether Apple",
    product: "aether-seed",
    productAmount: 40,
    workstation: "plant-extractor",
    duration: 60,
    cyclesPerMinuteOneStumpy: 1,
    ingredients: [{ item: "aether-apple", amount: 1 }],
    wiki: "https://oddsparks.wiki.gg/wiki/Aether_Seed",
  },
  {
    id: "aether-segment-extract-aether-apple-1-aether-apple",
    name: "Extract Aether Apple",
    product: "aether-segment",
    productAmount: 20,
    workstation: "extractor",
    duration: 60,
    cyclesPerMinuteOneStumpy: 1,
    ingredients: [{ item: "aether-apple", amount: 1 }],
    wiki: "https://oddsparks.wiki.gg/wiki/Aether_Segment",
  },
  {
    id: "aether-seed-extract-aether-segment-1-aether-segment",
    name: "Extract Aether Segment",
    product: "aether-seed",
    productAmount: 30,
    workstation: "plant-extractor",
    duration: 60,
    cyclesPerMinuteOneStumpy: 1,
    ingredients: [{ item: "aether-segment", amount: 1 }],
    wiki: "https://oddsparks.wiki.gg/wiki/Aether_Seed",
  },
  {
    id: "aether-crystal-extract-aether-segment-1-aether-segment",
    name: "Extract Aether Segment",
    product: "aether-crystal",
    productAmount: 5,
    workstation: "extractor",
    duration: 60,
    cyclesPerMinuteOneStumpy: 1,
    ingredients: [{ item: "aether-segment", amount: 1 }],
    wiki: "https://oddsparks.wiki.gg/wiki/Aether_Crystal",
  },
  {
    id: "aetheric-clump-extract-aether-flower-1-aether-flower",
    name: "Extract Aether Flower",
    product: "aetheric-clump",
    productAmount: 6,
    workstation: "extractor",
    duration: 60,
    cyclesPerMinuteOneStumpy: 1,
    ingredients: [{ item: "aether-flower", amount: 1 }],
    wiki: "https://oddsparks.wiki.gg/wiki/Aetheric_Clump",
  },
  {
    id: "aether-seed-extract-aether-flower-1-aether-flower",
    name: "Extract Aether Flower",
    product: "aether-seed",
    productAmount: 20,
    workstation: "plant-extractor",
    duration: 60,
    cyclesPerMinuteOneStumpy: 1,
    ingredients: [{ item: "aether-flower", amount: 1 }],
    wiki: "https://oddsparks.wiki.gg/wiki/Aether_Seed",
  },
  {
    id: "copper-sap-extract-copper-cuttings-1-copper-cuttings",
    name: "Extract Copper Cuttings",
    product: "copper-sap",
    productAmount: 20,
    workstation: "plant-extractor",
    duration: 60,
    cyclesPerMinuteOneStumpy: 1,
    ingredients: [{ item: "copper-cuttings", amount: 1 }],
    wiki: "https://oddsparks.wiki.gg/wiki/Copper_Sap",
  },
  {
    id: "copper-seed-extract-copper-cuttings-1-copper-cuttings",
    name: "Extract Copper Cuttings",
    product: "copper-seed",
    productAmount: 10,
    workstation: "plant-extractor",
    duration: 60,
    cyclesPerMinuteOneStumpy: 1,
    ingredients: [{ item: "copper-cuttings", amount: 1 }],
    wiki: "https://oddsparks.wiki.gg/wiki/Copper_Seed",
  },
  {
    id: "copper-ore-extract-copper-seed-2-copper-seed",
    name: "Extract Copper Seed",
    product: "copper-ore",
    productAmount: 1,
    workstation: "extractor",
    duration: 60,
    cyclesPerMinuteOneStumpy: 1,
    ingredients: [{ item: "copper-seed", amount: 2 }],
    wiki: "https://oddsparks.wiki.gg/wiki/Copper_Ore",
  },
  {
    id: "coal-extract-copper-seed-2-copper-seed",
    name: "Extract Copper Seed",
    product: "coal",
    productAmount: 1,
    workstation: "furnace",
    duration: 60,
    cyclesPerMinuteOneStumpy: 1,
    ingredients: [{ item: "copper-seed", amount: 2 }],
    wiki: "https://oddsparks.wiki.gg/wiki/Coal",
  },
  {
    id: "limestone-extract-coral-seed-1-coral-seed",
    name: "Extract Coral Seed",
    product: "limestone",
    productAmount: 3,
    workstation: "stonecutter",
    duration: 60,
    cyclesPerMinuteOneStumpy: 1,
    ingredients: [{ item: "coral-seed", amount: 1 }],
    wiki: "https://oddsparks.wiki.gg/wiki/Limestone",
  },
  {
    id: "coral-extract-coral-seed-1-coral-seed",
    name: "Extract Coral Seed",
    product: "coral",
    productAmount: 3,
    workstation: "extractor",
    duration: 60,
    cyclesPerMinuteOneStumpy: 1,
    ingredients: [{ item: "coral-seed", amount: 1 }],
    wiki: "https://oddsparks.wiki.gg/wiki/Coral",
  },
  {
    id: "glowshroom-extract-fireshroom-cluster-2-fireshroom-cluster",
    name: "Extract Fireshroom Cluster",
    product: "glowshroom",
    productAmount: 5,
    workstation: "extractor",
    duration: 60,
    cyclesPerMinuteOneStumpy: 1,
    ingredients: [{ item: "fireshroom-cluster", amount: 2 }],
    wiki: "https://oddsparks.wiki.gg/wiki/Glowshroom",
  },
  {
    id: "lava-cap-extract-fireshroom-cluster-2-fireshroom-cluster",
    name: "Extract Fireshroom Cluster",
    product: "lava-cap",
    productAmount: 5,
    workstation: "extractor",
    duration: 60,
    cyclesPerMinuteOneStumpy: 1,
    ingredients: [{ item: "fireshroom-cluster", amount: 2 }],
    wiki: "https://oddsparks.wiki.gg/wiki/Lava_Cap",
  },
  {
    id: "stone-extract-stellar-ice-4-stellar-ice",
    name: "Extract Stellar Ice",
    product: "stone",
    productAmount: 2,
    workstation: "stonecutter",
    duration: 60,
    cyclesPerMinuteOneStumpy: 1,
    ingredients: [{ item: "stellar-ice", amount: 4 }],
    wiki: "https://oddsparks.wiki.gg/wiki/Stone",
  },
  {
    id: "stellar-seed-extract-stellar-ice-4-stellar-ice",
    name: "Extract Stellar Ice",
    product: "stellar-seed",
    productAmount: 1,
    workstation: "plant-extractor",
    duration: 60,
    cyclesPerMinuteOneStumpy: 1,
    ingredients: [{ item: "stellar-ice", amount: 4 }],
    wiki: "https://oddsparks.wiki.gg/wiki/Stellar_Seed",
  },
  {
    id: "stellar-seed-extract-stellar-leaves-2-stellar-leaves",
    name: "Extract Stellar Leaves",
    product: "stellar-seed",
    productAmount: 3,
    workstation: "plant-extractor",
    duration: 60,
    cyclesPerMinuteOneStumpy: 1,
    ingredients: [{ item: "stellar-leaves", amount: 2 }],
    wiki: "https://oddsparks.wiki.gg/wiki/Stellar_Seed",
  },
  {
    id: "stellar-ice-extract-stellar-leaves-2-stellar-leaves",
    name: "Extract Stellar Leaves",
    product: "stellar-ice",
    productAmount: 5,
    workstation: "extractor",
    duration: 60,
    cyclesPerMinuteOneStumpy: 1,
    ingredients: [{ item: "stellar-leaves", amount: 2 }],
    wiki: "https://oddsparks.wiki.gg/wiki/Stellar_Ice",
  },
  {
    id: "fabric-fabric-4-tree-bark-2-rope",
    name: "Fabric",
    product: "fabric",
    productAmount: 1,
    workstation: "loom",
    duration: 8,
    cyclesPerMinuteOneStumpy: 7.5,
    ingredients: [
      { item: "tree-bark", amount: 4 },
      { item: "rope", amount: 2 },
    ],
    wiki: "https://oddsparks.wiki.gg/wiki/Fabric",
  },
  {
    id: "fertiliser-fertiliser-4-leaves",
    name: "Fertiliser",
    product: "fertiliser",
    productAmount: 2,
    workstation: "cutter",
    duration: 24,
    cyclesPerMinuteOneStumpy: 2.5,
    ingredients: [{ item: "leaves", amount: 4 }],
    wiki: "https://oddsparks.wiki.gg/wiki/Fertiliser",
  },
  {
    id: "fertiliser-fertiliser-enrichment-1-fertiliser-5-stellar-ice",
    name: "Fertiliser Enrichment",
    product: "fertiliser",
    productAmount: 4,
    workstation: "cutter",
    duration: 60,
    cyclesPerMinuteOneStumpy: 1,
    ingredients: [
      { item: "fertiliser", amount: 1 },
      { item: "stellar-ice", amount: 5 },
    ],
    wiki: "https://oddsparks.wiki.gg/wiki/Fertiliser",
  },
  {
    id: "stellar-ice-frozen-log-cutting-1-frozen-log",
    name: "Frozen Log Cutting",
    product: "stellar-ice",
    productAmount: 3,
    workstation: "sawbench",
    duration: 60,
    cyclesPerMinuteOneStumpy: 1,
    ingredients: [{ item: "frozen-log", amount: 1 }],
    wiki: "https://oddsparks.wiki.gg/wiki/Stellar_Ice",
  },
  {
    id: "stellar-ice-frozen-stone-cutting-2-frozen-stone",
    name: "Frozen Stone Cutting",
    product: "stellar-ice",
    productAmount: 6,
    workstation: "sawbench",
    duration: 60,
    cyclesPerMinuteOneStumpy: 1,
    ingredients: [{ item: "frozen-stone", amount: 2 }],
    wiki: "https://oddsparks.wiki.gg/wiki/Stellar_Ice",
  },
  {
    id: "miasma-vial-miasma-vial-2-small-vial-2-gas-poison",
    name: "Miasma Vial",
    product: "miasma-vial",
    productAmount: 2,
    workstation: "compressor",
    duration: 60,
    cyclesPerMinuteOneStumpy: 1,
    ingredients: [
      { item: "small-vial", amount: 2 },
      { item: "gas-poison", amount: 2 },
    ],
    wiki: "https://oddsparks.wiki.gg/wiki/Miasma_Vial",
  },
  {
    id: "tree-bark-bark-harvesting-raw",
    name: "Bark Harvesting",
    product: "tree-bark",
    productAmount: 1,
    workstation: "logger",
    duration: 2,
    cyclesPerMinuteOneStumpy: 30,
    ingredients: [],
    wiki: "https://oddsparks.wiki.gg/wiki/Tree_Bark",
  },
  {
    id: "clay-clay-raw",
    name: "Clay",
    product: "clay",
    productAmount: 1,
    workstation: "clay-digger",
    duration: 60,
    cyclesPerMinuteOneStumpy: 1,
    ingredients: [],
    wiki: "https://oddsparks.wiki.gg/wiki/Clay",
  },
  {
    id: "coal-coal-raw",
    name: "Coal",
    product: "coal",
    productAmount: 1,
    workstation: "furnace",
    duration: 60,
    cyclesPerMinuteOneStumpy: 1,
    ingredients: [],
    wiki: "https://oddsparks.wiki.gg/wiki/Coal",
  },
  {
    id: "leaves-leaves-harvesting-raw",
    name: "Leaves Harvesting",
    product: "leaves",
    productAmount: 1,
    workstation: "logger",
    duration: 2,
    cyclesPerMinuteOneStumpy: 30,
    ingredients: [],
    wiki: "https://oddsparks.wiki.gg/wiki/Leaves",
  },
  {
    id: "limestone-limestone-harvesting-raw",
    name: "Limestone Harvesting",
    product: "limestone",
    productAmount: 1,
    workstation: "drill",
    duration: 2,
    cyclesPerMinuteOneStumpy: 30,
    ingredients: [],
    wiki: "https://oddsparks.wiki.gg/wiki/Limestone",
  },
  {
    id: "wooden-log-log-harvesting-raw",
    name: "Log Harvesting",
    product: "wooden-log",
    productAmount: 1,
    workstation: "logger",
    duration: 2,
    cyclesPerMinuteOneStumpy: 30,
    ingredients: [],
    wiki: "https://oddsparks.wiki.gg/wiki/Wooden_Log",
  },
  {
    id: "copper-ore-copper-ore-harvesting-raw",
    name: "Copper Ore Harvesting",
    product: "copper-ore",
    productAmount: 1,
    workstation: "ore-miner",
    duration: 2,
    cyclesPerMinuteOneStumpy: 30,
    ingredients: [],
    wiki: "https://oddsparks.wiki.gg/wiki/Copper_Ore",
  },
  {
    id: "tree-bark-overclocked-bark-harvesting-raw",
    name: "Overclocked Bark Harvesting",
    product: "tree-bark",
    productAmount: 1,
    workstation: "logger",
    duration: 1,
    cyclesPerMinuteOneStumpy: 60,
    ingredients: [],
    wiki: "https://oddsparks.wiki.gg/wiki/Tree_Bark",
  },
  {
    id: "leaves-overclocked-leaves-harvesting-raw",
    name: "Overclocked Leaves Harvesting",
    product: "leaves",
    productAmount: 1,
    workstation: "logger",
    duration: 1,
    cyclesPerMinuteOneStumpy: 60,
    ingredients: [],
    wiki: "https://oddsparks.wiki.gg/wiki/Leaves",
  },
  {
    id: "limestone-overclocked-limestone-harvesting-raw",
    name: "Overclocked Limestone Harvesting",
    product: "limestone",
    productAmount: 1,
    workstation: "drill",
    duration: 1,
    cyclesPerMinuteOneStumpy: 60,
    ingredients: [],
    wiki: "https://oddsparks.wiki.gg/wiki/Limestone",
  },
  {
    id: "wooden-log-overclocked-log-harvesting-raw",
    name: "Overclocked Log Harvesting",
    product: "wooden-log",
    productAmount: 1,
    workstation: "logger",
    duration: 1,
    cyclesPerMinuteOneStumpy: 60,
    ingredients: [],
    wiki: "https://oddsparks.wiki.gg/wiki/Wooden_Log",
  },
  {
    id: "copper-ore-overclocked-copper-ore-harvesting-raw",
    name: "Overclocked Copper Ore Harvesting",
    product: "copper-ore",
    productAmount: 1,
    workstation: "ore-miner",
    duration: 1,
    cyclesPerMinuteOneStumpy: 60,
    ingredients: [],
    wiki: "https://oddsparks.wiki.gg/wiki/Copper_Ore",
  },
  {
    id: "quartz-overclocked-quartz-harvesting-raw",
    name: "Overclocked Quartz Harvesting",
    product: "quartz",
    productAmount: 1,
    workstation: "drill",
    duration: 1,
    cyclesPerMinuteOneStumpy: 60,
    ingredients: [],
    wiki: "https://oddsparks.wiki.gg/wiki/Quartz",
  },
  {
    id: "stone-overclocked-stone-harvesting-raw",
    name: "Overclocked Stone Harvesting",
    product: "stone",
    productAmount: 1,
    workstation: "drill",
    duration: 1,
    cyclesPerMinuteOneStumpy: 60,
    ingredients: [],
    wiki: "https://oddsparks.wiki.gg/wiki/Stone",
  },
  {
    id: "quartz-quartz-harvesting-raw",
    name: "Quartz Harvesting",
    product: "quartz",
    productAmount: 1,
    workstation: "drill",
    duration: 2,
    cyclesPerMinuteOneStumpy: 30,
    ingredients: [],
    wiki: "https://oddsparks.wiki.gg/wiki/Quartz",
  },
  {
    id: "stone-stone-harvesting-raw",
    name: "Stone Harvesting",
    product: "stone",
    productAmount: 1,
    workstation: "drill",
    duration: 2,
    cyclesPerMinuteOneStumpy: 30,
    ingredients: [],
    wiki: "https://oddsparks.wiki.gg/wiki/Stone",
  },
  {
    id: "ladder-ladder-4-wooden-log-10-sawn-timber",
    name: "Ladder",
    product: "ladder",
    productAmount: 2,
    workstation: "wood-workshop",
    duration: 32,
    cyclesPerMinuteOneStumpy: 1.875,
    ingredients: [
      { item: "wooden-log", amount: 4 },
      { item: "sawn-timber", amount: 10 },
    ],
    wiki: "https://oddsparks.wiki.gg/wiki/Ladder",
  },
  {
    id: "leaves-leaf-knot-cutting-1-leaf-knot",
    name: "Leaf Knot Cutting",
    product: "leaves",
    productAmount: 10,
    workstation: "sawbench",
    duration: 60,
    cyclesPerMinuteOneStumpy: 1,
    ingredients: [{ item: "leaf-knot", amount: 1 }],
    wiki: "https://oddsparks.wiki.gg/wiki/Leaves",
  },
  {
    id: "wooden-log-leaf-knot-trimming-1-leaf-knot",
    name: "Leaf Knot Trimming",
    product: "wooden-log",
    productAmount: 6,
    workstation: "sawbench",
    duration: 60,
    cyclesPerMinuteOneStumpy: 1,
    ingredients: [{ item: "leaf-knot", amount: 1 }],
    wiki: "https://oddsparks.wiki.gg/wiki/Wooden_Log",
  },
  {
    id: "limestone-limestone-4-coral",
    name: "Limestone",
    product: "limestone",
    productAmount: 3,
    workstation: "stonecutter",
    duration: 16,
    cyclesPerMinuteOneStumpy: 3.75,
    ingredients: [{ item: "coral", amount: 4 }],
    wiki: "https://oddsparks.wiki.gg/wiki/Limestone",
  },
  {
    id: "liquid-fertiliser-liquid-fertiliser-2-fireshroom-cluster-1-stellar-leaves",
    name: "Liquid Fertiliser",
    product: "liquid-fertiliser",
    productAmount: 4,
    workstation: "cutter",
    duration: 60,
    cyclesPerMinuteOneStumpy: 1,
    ingredients: [
      { item: "fireshroom-cluster", amount: 2 },
      { item: "stellar-leaves", amount: 1 },
    ],
    wiki: "https://oddsparks.wiki.gg/wiki/Liquid_Fertiliser",
  },
  {
    id: "handy-spark-handy-spark-5-crafty-spark-4-copper-ingot-1-aether-crystal",
    name: "Handy Spark",
    product: "handy-spark",
    productAmount: 1,
    workstation: "metal-spark-workstation",
    duration: 64,
    cyclesPerMinuteOneStumpy: 0.9,
    ingredients: [
      { item: "crafty-spark", amount: 5 },
      { item: "copper-ingot", amount: 4 },
      { item: "aether-crystal", amount: 1 },
    ],
    wiki: "https://oddsparks.wiki.gg/wiki/Handy_Spark",
  },
  {
    id: "burning-spark-burning-spark-5-lava-cap-8-copper-ingot-1-aether-crystal",
    name: "Burning Spark",
    product: "burning-spark",
    productAmount: 1,
    workstation: "metal-spark-workstation",
    duration: 60,
    cyclesPerMinuteOneStumpy: 1,
    ingredients: [
      { item: "lava-cap", amount: 5 },
      { item: "copper-ingot", amount: 8 },
      { item: "aether-crystal", amount: 1 },
    ],
    wiki: "https://oddsparks.wiki.gg/wiki/Burning_Spark",
  },
  {
    id: "freezing-spark-freezing-spark-10-stellar-ice-8-copper-ingot-1-aether-crystal",
    name: "Freezing Spark",
    product: "freezing-spark",
    productAmount: 1,
    workstation: "metal-spark-workstation",
    duration: 60,
    cyclesPerMinuteOneStumpy: 1,
    ingredients: [
      { item: "stellar-ice", amount: 10 },
      { item: "copper-ingot", amount: 8 },
      { item: "aether-crystal", amount: 1 },
    ],
    wiki: "https://oddsparks.wiki.gg/wiki/Freezing_Spark",
  },
  {
    id: "drilly-spark-drilly-spark-6-slashy-spark-3-drill-bit-3-aether-crystal",
    name: "Drilly Spark",
    product: "drilly-spark",
    productAmount: 3,
    workstation: "metal-spark-workstation",
    duration: 64,
    cyclesPerMinuteOneStumpy: 0.938,
    ingredients: [
      { item: "slashy-spark", amount: 6 },
      { item: "drill-bit", amount: 3 },
      { item: "aether-crystal", amount: 3 },
    ],
    wiki: "https://oddsparks.wiki.gg/wiki/Drilly_Spark",
  },
  {
    id: "scrubby-spark-scrubby-spark-2-sponge-4-copper-ingot-1-aether-crystal",
    name: "Scrubby Spark",
    product: "scrubby-spark",
    productAmount: 1,
    workstation: "metal-spark-workstation",
    duration: 60,
    cyclesPerMinuteOneStumpy: 1,
    ingredients: [
      { item: "sponge", amount: 2 },
      { item: "copper-ingot", amount: 4 },
      { item: "aether-crystal", amount: 1 },
    ],
    wiki: "https://oddsparks.wiki.gg/wiki/Scrubby_Spark",
  },
  {
    id: "scouty-spark-scouty-spark-1-stumpy-spark-1-dowsing-stone",
    name: "Scouty Spark",
    product: "scouty-spark",
    productAmount: 1,
    workstation: "spark-workstation",
    duration: 32,
    cyclesPerMinuteOneStumpy: 1.875,
    ingredients: [
      { item: "stumpy-spark", amount: 1 },
      { item: "dowsing-stone", amount: 1 },
    ],
    wiki: "https://oddsparks.wiki.gg/wiki/Scouty_Spark",
  },
  {
    id: "loamy-spark-loamy-spark-5-aether-shard-3-fertiliser",
    name: "Loamy Spark",
    product: "loamy-spark",
    productAmount: 5,
    workstation: "spark-workbench",
    duration: 32,
    cyclesPerMinuteOneStumpy: 1.875,
    ingredients: [
      { item: "aether-shard", amount: 5 },
      { item: "fertiliser", amount: 3 },
    ],
    wiki: "https://oddsparks.wiki.gg/wiki/Loamy_Spark",
  },
  {
    id: "puffy-spark-puffy-spark-1-rocky-spark-4-fabric",
    name: "Puffy Spark",
    product: "puffy-spark",
    productAmount: 1,
    workstation: "spark-workstation",
    duration: 32,
    cyclesPerMinuteOneStumpy: 1.875,
    ingredients: [
      { item: "rocky-spark", amount: 1 },
      { item: "fabric", amount: 4 },
    ],
    wiki: "https://oddsparks.wiki.gg/wiki/Puffy_Spark",
  },
  {
    id: "boomy-spark-boomy-spark-3-rocky-spark-5-explosive",
    name: "Boomy Spark",
    product: "boomy-spark",
    productAmount: 3,
    workstation: "spark-workstation",
    duration: 48,
    cyclesPerMinuteOneStumpy: 1.25,
    ingredients: [
      { item: "rocky-spark", amount: 3 },
      { item: "explosive", amount: 5 },
    ],
    wiki: "https://oddsparks.wiki.gg/wiki/Boomy_Spark",
  },
  {
    id: "hauling-spark-hauling-spark-2-carry-spark-4-stone-wheel",
    name: "Hauling Spark",
    product: "hauling-spark",
    productAmount: 1,
    workstation: "spark-workstation",
    duration: 64,
    cyclesPerMinuteOneStumpy: 0.938,
    ingredients: [
      { item: "carry-spark", amount: 2 },
      { item: "stone-wheel", amount: 4 },
    ],
    wiki: "https://oddsparks.wiki.gg/wiki/Hauling_Spark",
  },
  {
    id: "rocky-spark-rocky-spark-2-stumpy-spark-5-stone",
    name: "Rocky Spark",
    product: "rocky-spark",
    productAmount: 1,
    workstation: "spark-workstation",
    duration: 32,
    cyclesPerMinuteOneStumpy: 1.875,
    ingredients: [
      { item: "stumpy-spark", amount: 2 },
      { item: "stone", amount: 5 },
    ],
    wiki: "https://oddsparks.wiki.gg/wiki/Rocky_Spark",
  },
  {
    id: "crashy-spark-crashy-spark-2-boomy-spark-7-stone-spike",
    name: "Crashy Spark",
    product: "crashy-spark",
    productAmount: 1,
    workstation: "spark-workstation",
    duration: 64,
    cyclesPerMinuteOneStumpy: 0.938,
    ingredients: [
      { item: "boomy-spark", amount: 2 },
      { item: "stone-spike", amount: 7 },
    ],
    wiki: "https://oddsparks.wiki.gg/wiki/Crashy_Spark",
  },
  {
    id: "slashy-spark-slashy-spark-2-rocky-spark-3-choppy-spark",
    name: "Slashy Spark",
    product: "slashy-spark",
    productAmount: 1,
    workstation: "spark-workstation",
    duration: 64,
    cyclesPerMinuteOneStumpy: 0.938,
    ingredients: [
      { item: "rocky-spark", amount: 2 },
      { item: "choppy-spark", amount: 3 },
    ],
    wiki: "https://oddsparks.wiki.gg/wiki/Slashy_Spark",
  },
  {
    id: "arty-spark-arty-spark-2-stumpy-spark-5-rope",
    name: "Arty Spark",
    product: "arty-spark",
    productAmount: 1,
    workstation: "spark-workbench",
    duration: 32,
    cyclesPerMinuteOneStumpy: 1.9,
    ingredients: [
      { item: "stumpy-spark", amount: 2 },
      { item: "rope", amount: 5 },
    ],
    wiki: "https://oddsparks.wiki.gg/wiki/Arty_Spark",
  },
  {
    id: "carry-spark-carry-spark-1-crafty-spark-4-sawn-timber",
    name: "Carry Spark",
    product: "carry-spark",
    productAmount: 1,
    workstation: "spark-workbench",
    duration: 32,
    cyclesPerMinuteOneStumpy: 1.875,
    ingredients: [
      { item: "crafty-spark", amount: 1 },
      { item: "sawn-timber", amount: 4 },
    ],
    wiki: "https://oddsparks.wiki.gg/wiki/Carry_Spark",
  },
  {
    id: "stumpy-spark-stumpy-spark-1-aether-shard-5-wooden-log",
    name: "Stumpy Spark",
    product: "stumpy-spark",
    productAmount: 1,
    workstation: "spark-workbench",
    duration: 32,
    cyclesPerMinuteOneStumpy: 1.875,
    ingredients: [
      { item: "aether-shard", amount: 1 },
      { item: "wooden-log", amount: 5 },
    ],
    wiki: "https://oddsparks.wiki.gg/wiki/Stumpy_Spark",
  },
  {
    id: "choppy-spark-choppy-spark-3-stumpy-spark-1-wooden-blade",
    name: "Choppy Spark",
    product: "choppy-spark",
    productAmount: 1,
    workstation: "spark-workbench",
    duration: 64,
    cyclesPerMinuteOneStumpy: 0.938,
    ingredients: [
      { item: "stumpy-spark", amount: 3 },
      { item: "wooden-blade", amount: 1 },
    ],
    wiki: "https://oddsparks.wiki.gg/wiki/Choppy_Spark",
  },
  {
    id: "crafty-spark-crafty-spark-2-stumpy-spark-2-wooden-panel",
    name: "Crafty Spark",
    product: "crafty-spark",
    productAmount: 1,
    workstation: "spark-workbench",
    duration: 48,
    cyclesPerMinuteOneStumpy: 1.25,
    ingredients: [
      { item: "stumpy-spark", amount: 2 },
      { item: "wooden-panel", amount: 2 },
    ],
    wiki: "https://oddsparks.wiki.gg/wiki/Crafty_Spark",
  },
  {
    id: "path-tile-path-tile-10-pebble-5-limestone",
    name: "Path Tile",
    product: "path-tile",
    productAmount: 5,
    workstation: "stone-workshop",
    duration: 32,
    cyclesPerMinuteOneStumpy: 1.875,
    ingredients: [
      { item: "pebble", amount: 10 },
      { item: "limestone", amount: 5 },
    ],
    wiki: "https://oddsparks.wiki.gg/wiki/Path_Tile",
  },
  {
    id: "pebble-pebble-1-stone",
    name: "Pebble",
    product: "pebble",
    productAmount: 2,
    workstation: "stonecutter",
    duration: 32,
    cyclesPerMinuteOneStumpy: 1.875,
    ingredients: [{ item: "stone", amount: 1 }],
    wiki: "https://oddsparks.wiki.gg/wiki/Pebble",
  },
  {
    id: "big-vial-big-vial-10-quartz",
    name: "Big Vial",
    product: "big-vial",
    productAmount: 2,
    workstation: "furnace",
    duration: 128,
    cyclesPerMinuteOneStumpy: 0.46875,
    ingredients: [{ item: "quartz", amount: 10 }],
    wiki: "https://oddsparks.wiki.gg/wiki/Big_Vial",
  },
  {
    id: "small-vial-small-vial-4-quartz",
    name: "Small Vial",
    product: "small-vial",
    productAmount: 2,
    workstation: "furnace",
    duration: 32,
    cyclesPerMinuteOneStumpy: 1.875,
    ingredients: [{ item: "quartz", amount: 4 }],
    wiki: "https://oddsparks.wiki.gg/wiki/Small_Vial",
  },
  {
    id: "raw-aether-miasma-transmutation-2-miasma-vial-1-aether-shard",
    name: "Miasma Transmutation",
    product: "raw-aether",
    productAmount: 1,
    workstation: "alchemy-station",
    duration: 48,
    cyclesPerMinuteOneStumpy: 1.25,
    ingredients: [
      { item: "miasma-vial", amount: 2 },
      { item: "aether-shard", amount: 1 },
    ],
    wiki: "https://oddsparks.wiki.gg/wiki/Raw_Aether",
  },
  {
    id: "aether-shard-raw-distillation-1-raw-aether",
    name: "Raw Distillation",
    product: "aether-shard",
    productAmount: 6,
    workstation: "aetheric-collider",
    duration: 48,
    cyclesPerMinuteOneStumpy: 1.25,
    ingredients: [{ item: "raw-aether", amount: 1 }],
    wiki: "https://oddsparks.wiki.gg/wiki/Aether_Shard",
  },
  {
    id: "refined-aether-raw-aether-purification-2-raw-aether",
    name: "Raw Aether Purification",
    product: "refined-aether",
    productAmount: 1,
    workstation: "alchemy-station",
    duration: 60,
    cyclesPerMinuteOneStumpy: 1,
    ingredients: [{ item: "raw-aether", amount: 2 }],
    wiki: "https://oddsparks.wiki.gg/wiki/Refined_Aether",
  },
  {
    id: "refined-aether-aether-refinement-4-raw-aether-1-big-vial",
    name: "Aether Refinement",
    product: "refined-aether",
    productAmount: 1,
    workstation: "compressor",
    duration: 64,
    cyclesPerMinuteOneStumpy: 0.9375,
    ingredients: [
      { item: "raw-aether", amount: 4 },
      { item: "big-vial", amount: 1 },
    ],
    wiki: "https://oddsparks.wiki.gg/wiki/Refined_Aether",
  },
  {
    id: "aether-crystal-aether-crystal-1-refined-aether",
    name: "Aether Crystal",
    product: "aether-crystal",
    productAmount: 1,
    workstation: "compressor",
    duration: 60,
    cyclesPerMinuteOneStumpy: 1,
    ingredients: [{ item: "refined-aether", amount: 1 }],
    wiki: "https://oddsparks.wiki.gg/wiki/Aether_Crystal",
  },
  {
    id: "aether-shard-refined-distillation-1-refined-aether",
    name: "Refined Distillation",
    product: "aether-shard",
    productAmount: 30,
    workstation: "aetheric-collider",
    duration: 128,
    cyclesPerMinuteOneStumpy: 0.46875,
    ingredients: [{ item: "refined-aether", amount: 1 }],
    wiki: "https://oddsparks.wiki.gg/wiki/Aether_Shard",
  },
  {
    id: "sawn-timber-sawn-timber-2-wooden-log",
    name: "Sawn Timber",
    product: "sawn-timber",
    productAmount: 1,
    workstation: "sawbench",
    duration: 16,
    cyclesPerMinuteOneStumpy: 3.75,
    ingredients: [{ item: "wooden-log", amount: 2 }],
    wiki: "https://oddsparks.wiki.gg/wiki/Sawn_Timber",
  },
  {
    id: "wooden-panel-wooden-panel-2-sawn-timber",
    name: "Wooden Panel",
    product: "wooden-panel",
    productAmount: 1,
    workstation: "sawbench",
    duration: 8,
    cyclesPerMinuteOneStumpy: 7.5,
    ingredients: [{ item: "sawn-timber", amount: 2 }],
    wiki: "https://oddsparks.wiki.gg/wiki/Wooden_Panel",
  },
  {
    id: "rope-rope-2-leaves-1-tree-bark",
    name: "Rope",
    product: "rope",
    productAmount: 1,
    workstation: "loom",
    duration: 16,
    cyclesPerMinuteOneStumpy: 3.75,
    ingredients: [
      { item: "leaves", amount: 2 },
      { item: "tree-bark", amount: 1 },
    ],
    wiki: "https://oddsparks.wiki.gg/wiki/Rope",
  },
  {
    id: "fertiliser-soil-processing-1-volcanic-soil",
    name: "Soil Processing",
    product: "fertiliser",
    productAmount: 2,
    workstation: "cutter",
    duration: 60,
    cyclesPerMinuteOneStumpy: 1,
    ingredients: [{ item: "volcanic-soil", amount: 1 }],
    wiki: "https://oddsparks.wiki.gg/wiki/Fertiliser",
  },
  {
    id: "sponge-sponge-5-tree-bark-10-fabric",
    name: "Sponge",
    product: "sponge",
    productAmount: 3,
    workstation: "loom",
    duration: 60,
    cyclesPerMinuteOneStumpy: 1,
    ingredients: [
      { item: "tree-bark", amount: 5 },
      { item: "fabric", amount: 10 },
    ],
    wiki: "https://oddsparks.wiki.gg/wiki/Sponge",
  },
  {
    id: "stellar-fertiliser-stellar-fertiliser-4-fertiliser-1-stellar-leaves",
    name: "Stellar Fertiliser",
    product: "stellar-fertiliser",
    productAmount: 4,
    workstation: "cutter",
    duration: 60,
    cyclesPerMinuteOneStumpy: 1,
    ingredients: [
      { item: "fertiliser", amount: 4 },
      { item: "stellar-leaves", amount: 1 },
    ],
    wiki: "https://oddsparks.wiki.gg/wiki/Stellar_Fertiliser",
  },
  {
    id: "stone-stone-4-limestone",
    name: "Stone",
    product: "stone",
    productAmount: 2,
    workstation: "stonecutter",
    duration: 60,
    cyclesPerMinuteOneStumpy: 1,
    ingredients: [{ item: "limestone", amount: 4 }],
    wiki: "https://oddsparks.wiki.gg/wiki/Stone",
  },
  {
    id: "stone-block-stone-block-10-limestone-10-stone-plate",
    name: "Stone Block",
    product: "stone-block",
    productAmount: 5,
    workstation: "stone-workshop",
    duration: 60,
    cyclesPerMinuteOneStumpy: 1,
    ingredients: [
      { item: "limestone", amount: 10 },
      { item: "stone-plate", amount: 10 },
    ],
    wiki: "https://oddsparks.wiki.gg/wiki/Stone_Block",
  },
  {
    id: "stone-spike-stone-block-cutting-1-stone-block",
    name: "Stone Block Cutting",
    product: "stone-spike",
    productAmount: 1,
    workstation: "stonecutter",
    duration: 60,
    cyclesPerMinuteOneStumpy: 1,
    ingredients: [{ item: "stone-block", amount: 1 }],
    wiki: "https://oddsparks.wiki.gg/wiki/Stone_Spike",
  },
  {
    id: "stone-stone-block-breakdown-1-stone-block",
    name: "Stone Block Breakdown",
    product: "stone",
    productAmount: 8,
    workstation: "stonecutter",
    duration: 60,
    cyclesPerMinuteOneStumpy: 1,
    ingredients: [{ item: "stone-block", amount: 1 }],
    wiki: "https://oddsparks.wiki.gg/wiki/Stone",
  },
  {
    id: "stone-plate-stone-plate-2-stone",
    name: "Stone Plate",
    product: "stone-plate",
    productAmount: 1,
    workstation: "stonecutter",
    duration: 32,
    cyclesPerMinuteOneStumpy: 1.875,
    ingredients: [{ item: "stone", amount: 2 }],
    wiki: "https://oddsparks.wiki.gg/wiki/Stone_Plate",
  },
  {
    id: "stone-spike-stone-spike-1-wooden-blade-4-stone-plate",
    name: "Stone Spike",
    product: "stone-spike",
    productAmount: 4,
    workstation: "stone-workshop",
    duration: 16,
    cyclesPerMinuteOneStumpy: 3.75,
    ingredients: [
      { item: "wooden-blade", amount: 1 },
      { item: "stone-plate", amount: 4 },
    ],
    wiki: "https://oddsparks.wiki.gg/wiki/Stone_Spike",
  },
  {
    id: "quartz-quartz-3-limestone",
    name: "Quartz",
    product: "quartz",
    productAmount: 1,
    workstation: "stonecutter",
    duration: 60,
    cyclesPerMinuteOneStumpy: 1,
    ingredients: [{ item: "limestone", amount: 3 }],
    wiki: "https://oddsparks.wiki.gg/wiki/Quartz",
  },
  {
    id: "stone-wheel-stone-wheel-4-path-tile-2-stone-plate",
    name: "Stone Wheel",
    product: "stone-wheel",
    productAmount: 2,
    workstation: "stone-workshop",
    duration: 16,
    cyclesPerMinuteOneStumpy: 3.75,
    ingredients: [
      { item: "path-tile", amount: 4 },
      { item: "stone-plate", amount: 2 },
    ],
    wiki: "https://oddsparks.wiki.gg/wiki/Stone_Wheel",
  },
  {
    id: "wooden-blade-wooden-blade-1-sawn-timber-2-wooden-panel",
    name: "Wooden Blade",
    product: "wooden-blade",
    productAmount: 1,
    workstation: "wood-workshop",
    duration: 48,
    cyclesPerMinuteOneStumpy: 1.25,
    ingredients: [
      { item: "sawn-timber", amount: 1 },
      { item: "wooden-panel", amount: 2 },
    ],
    wiki: "https://oddsparks.wiki.gg/wiki/Wooden_Blade",
  },
  {
    id: "coal-coal-3-wooden-log",
    name: "Coal",
    product: "coal",
    productAmount: 1,
    workstation: "furnace",
    duration: 60,
    cyclesPerMinuteOneStumpy: 1,
    ingredients: [{ item: "wooden-log", amount: 3 }],
    wiki: "https://oddsparks.wiki.gg/wiki/Coal",
  },
];

export const outputItems = recipes
  .map((recipe) => recipe.product)
  .filter((id, index, all) => all.indexOf(id) === index);

export const recipesByProduct = recipes.reduce(
  (accumulator, recipe) => {
    accumulator[recipe.product] = [...(accumulator[recipe.product] ?? []), recipe];
    return accumulator;
  },
  {} as Partial<Record<ItemId, Recipe[]>>,
);

export const defaultRecipeIdByProduct: Partial<Record<ItemId, string>> = {
  "aether-crystal": "aether-crystal-aether-seed-crystallisation-1-aether-seed-1-raw-aether",
  "aether-seed": "aether-seed-extract-aether-apple-1-aether-apple",
  "aether-segment": "aether-segment-extract-aether-apple-1-aether-apple",
  "aether-shard": "aether-shard-aether-shard-raw",
  "aetheric-clump": "aetheric-clump-aether-clump-fusion-1-leaf-knot-1-refined-aether",
  "aetheric-pellet": "aetheric-pellet-clump-dividing-1-aetheric-clump",
  "arty-spark": "arty-spark-arty-spark-2-stumpy-spark-5-rope",
  "big-vial": "big-vial-big-vial-10-quartz",
  "boomy-spark": "boomy-spark-boomy-spark-3-rocky-spark-5-explosive",
  "bumpy-geode": "bumpy-geode-break-geode-cluster-1-geode-cluster",
  "burning-spark": "burning-spark-burning-spark-5-lava-cap-8-copper-ingot-1-aether-crystal",
  "carry-spark": "carry-spark-carry-spark-1-crafty-spark-4-sawn-timber",
  "choppy-spark": "choppy-spark-choppy-spark-3-stumpy-spark-1-wooden-blade",
  clay: "clay-clay-raw",
  "cleansing-fragment": "cleansing-fragment-cleansing-fragment-enrichment-4-grey-aether-18-cleansing-fragment",
  coal: "coal-coal-raw",
  "copper-ingot": "copper-ingot-copper-ore-smelting-3-copper-ore",
  "copper-ore": "copper-ore-copper-ore-harvesting-raw",
  "copper-sap": "copper-sap-extract-copper-cuttings-1-copper-cuttings",
  "copper-seed": "copper-seed-copper-sap-beading-1-copper-sap",
  coral: "coral-coral-1-fluted-coral",
  "cracked-geode": "cracked-geode-break-geode-cluster-1-geode-cluster",
  "crafty-spark": "crafty-spark-crafty-spark-2-stumpy-spark-2-wooden-panel",
  "crashy-spark": "crashy-spark-crashy-spark-2-boomy-spark-7-stone-spike",
  "dowsing-stone": "dowsing-stone-dowsing-stone-1-quartz-1-rope",
  "drill-bit": "drill-bit-drill-bit-2-copper-ingot",
  "drilly-spark": "drilly-spark-drilly-spark-6-slashy-spark-3-drill-bit-3-aether-crystal",
  explosive: "explosive-explosives-2-fertiliser-4-limestone",
  fabric: "fabric-fabric-4-tree-bark-2-rope",
  fertiliser: "fertiliser-fertiliser-4-leaves",
  "freezing-spark": "freezing-spark-freezing-spark-10-stellar-ice-8-copper-ingot-1-aether-crystal",
  glowshroom: "glowshroom-break-bumpy-geode-1-bumpy-geode",
  "grey-aether": "grey-aether-spark-token-cleansing-1-corrupted-spark-token-2-cleansing-fragment",
  "handy-spark": "handy-spark-handy-spark-5-crafty-spark-4-copper-ingot-1-aether-crystal",
  "hauling-spark": "hauling-spark-hauling-spark-2-carry-spark-4-stone-wheel",
  ladder: "ladder-ladder-4-wooden-log-10-sawn-timber",
  "lava-cap": "lava-cap-extract-fireshroom-cluster-2-fireshroom-cluster",
  leaves: "leaves-leaves-harvesting-raw",
  limestone: "limestone-limestone-harvesting-raw",
  "liquid-fertiliser": "liquid-fertiliser-liquid-fertiliser-2-fireshroom-cluster-1-stellar-leaves",
  "loamy-spark": "loamy-spark-loamy-spark-5-aether-shard-3-fertiliser",
  "miasma-vial": "miasma-vial-miasma-vial-2-small-vial-2-gas-poison",
  "path-tile": "path-tile-path-tile-10-pebble-5-limestone",
  pebble: "pebble-pebble-1-stone",
  "puffy-spark": "puffy-spark-puffy-spark-1-rocky-spark-4-fabric",
  quartz: "quartz-quartz-harvesting-raw",
  "raw-aether": "raw-aether-corrupted-aether-cleansing-2-corrupted-aether-1-cleansing-fragment",
  "refined-aether": "refined-aether-raw-aether-purification-2-raw-aether",
  "rocky-spark": "rocky-spark-rocky-spark-2-stumpy-spark-5-stone",
  rope: "rope-rope-2-leaves-1-tree-bark",
  "sawn-timber": "sawn-timber-sawn-timber-2-wooden-log",
  "scouty-spark": "scouty-spark-scouty-spark-1-stumpy-spark-1-dowsing-stone",
  "scrubby-spark": "scrubby-spark-spark-token-cleansing-1-corrupted-spark-token-2-cleansing-fragment",
  "shiny-geode": "shiny-geode-break-geode-cluster-1-geode-cluster",
  "slashy-spark": "slashy-spark-slashy-spark-2-rocky-spark-3-choppy-spark",
  "small-vial": "small-vial-small-vial-4-quartz",
  sponge: "sponge-sponge-5-tree-bark-10-fabric",
  "stellar-fertiliser": "stellar-fertiliser-stellar-fertiliser-4-fertiliser-1-stellar-leaves",
  "stellar-ice": "stellar-ice-extract-stellar-leaves-2-stellar-leaves",
  "stellar-seed": "stellar-seed-extract-stellar-ice-4-stellar-ice",
  stone: "stone-stone-harvesting-raw",
  "stone-block": "stone-block-stone-block-10-limestone-10-stone-plate",
  "stone-plate": "stone-plate-stone-plate-2-stone",
  "stone-spike": "stone-spike-stone-block-cutting-1-stone-block",
  "stone-wheel": "stone-wheel-stone-wheel-4-path-tile-2-stone-plate",
  "stumpy-spark": "stumpy-spark-stumpy-spark-1-aether-shard-5-wooden-log",
  "tree-bark": "tree-bark-bark-harvesting-raw",
  "volcanic-soil": "volcanic-soil-break-bumpy-geode-1-bumpy-geode",
  "wooden-blade": "wooden-blade-wooden-blade-1-sawn-timber-2-wooden-panel",
  "wooden-log": "wooden-log-log-harvesting-raw",
  "wooden-panel": "wooden-panel-wooden-panel-2-sawn-timber",
};

export const crewOptions = [
  {
    id: "stumpy-1",
    label: "1 Stumpy",
    multiplier: 1,
    sparks: ["stumpy-spark"] satisfies ItemId[],
  },
  {
    id: "stumpy-2",
    label: "2 Stumpy",
    multiplier: 2,
    sparks: ["stumpy-spark", "stumpy-spark"] satisfies ItemId[],
  },
  {
    id: "crafty-1",
    label: "1 Crafty",
    multiplier: 1.5,
    sparks: ["crafty-spark"] satisfies ItemId[],
  },
  {
    id: "crafty-2",
    label: "2 Crafty",
    multiplier: 3,
    sparks: ["crafty-spark", "crafty-spark"] satisfies ItemId[],
  },
  {
    id: "mixed-1-1",
    label: "1 Stumpy + 1 Crafty",
    multiplier: 2.5,
    sparks: ["stumpy-spark", "crafty-spark"] satisfies ItemId[],
  },
] as const;

export type CrewOptionId = (typeof crewOptions)[number]["id"];
